### ISSUE TITLE
Fix the 404 Page

### ISSUE THREAD

**Issue by swapnilsparsh** [swapnilsparsh/DevEmpire#102]
1. Fix the size of SVG
2. Fix the CSS of the `Back to Home` Button

![Screenshot 2022-02-14 145335](https://user-images.githubusercontent.com/69387608/153836067-4515dfa7-6279-4f02-9ebf-7f52fac1e951.png)

**Comment by rockingrohit9639** [comment]
> 1. Fix the size of SVG
> 2. Fix the CSS of the `Back to Home` Button
> 
> ![Screenshot 2022-02-14 145335](https://user-images.githubusercontent.com/69387608/153836067-4515dfa7-6279-4f02-9ebf-7f52fac1e951.png)

I would like to work on this issue. @swapnilsparsh
