### ISSUE TITLE
Make a 500 Page

### ISSUE THREAD

**Issue by swapnilsparsh** [swapnilsparsh/DevEmpire#103]
Make a new file in the pages folder and name it 505.js and start the work here.
[Reference](https://nextjs.org/docs/advanced-features/custom-error-page)

**Comment by shubhsardana29** [comment]
I am a GSSOC'22 participant, I want to work on this issue.

**Comment by Rituresh143** [comment]
if in case he is not able to work please assign to me

**Comment by shubhsardana29** [comment]
@swapnilsparsh please add GSSOC'22 label
