### ISSUE TITLE
Landing Page SVG

### ISSUE THREAD

**Issue by swapnilsparsh** [swapnilsparsh/DevEmpire#104]
Landing Page SVG taking more time than expected to load so optimize/fix it

**Comment by mishra811** [comment]
Hey can you please assign me this issue to work on

**Comment by swapnilsparsh** [comment]
@mishra811 Good Luck 👍🏻

**Comment by mishra811** [comment]
@swapnilsparsh which branch do I have to work on?

**Comment by MitAbhay** [comment]
@swapnilsparsh  I want to do this issue, can you assign it to me?

**Comment by mayank-del** [comment]
@swapnilsparsh  can you assign this to me, I should also get an opportunity to work  under this issue?

**Comment by navyasharma0203** [comment]
@swapnilsparsh can I work on this issue??

**Comment by mayank-del** [comment]
> > @swapnilsparsh can I work on this issue??
> 
> Good Luck 👍🏻

@swapnilsparsh sir, it is not even 7days how you can unassigned me in 5 days.

**Comment by swapnilsparsh** [comment]
> > > @swapnilsparsh can I work on this issue??
> > 
> > Good Luck 👍🏻
> 
> @swapnilsparsh sir, it is not even 7days how you can unassigned me in 5 days.

You are working on multiple issue and it's 5 days where there is no update of your work.

**Comment by swapnilsparsh** [comment]
> Landing Page SVG taking more time than expected to load so optimize/fix it

![SVG](https://user-images.githubusercontent.com/69387608/183276561-af6c35e8-16f4-412b-b008-b23b2e0456df.png)
