### ISSUE TITLE
Make a global search bar at landing page

### ISSUE THREAD

**Issue by swapnilsparsh** [swapnilsparsh/DevEmpire#106]

**Comment by yasledesma** [comment]
I think I could implement something like this. Sorry to sound like a newbie, but I am, and I wonder if it should search for the Ambassador
, Programs
, Web Dev
, JS Toolkits data?

If I got it right, I would like to take on this issue as a GsSoC contributor.

**Comment by swapnilsparsh** [comment]
> I think I could implement something like this. Sorry to sound like a newbie, but I am, and I wonder if it should search for the Ambassador , Programs , Web Dev , JS Toolkits data?
> 
> If I got it right, I would like to take on this issue as a GsSoC contributor.

Yes, it will work that way only.

**Comment by nalin-singh** [comment]
I would like to work on this task for SSOC '22

**Comment by swapnilsparsh** [comment]
> I would like to work on this task for SSOC '22

Good Luck 👍🏻

**Comment by Yash-Raj-50** [comment]
Can I work on this task for KWOC ?

**Comment by Yash-Raj-50** [comment]
Is there any expected design available for the global search? Like the position of searchbox and search results.

**Comment by swapnilsparsh** [comment]
Resolved by @Yash-Raj-50
