### ISSUE TITLE
Restyle Navbar

### ISSUE THREAD

**Issue by swapnilsparsh** [swapnilsparsh/DevEmpire#107]
Restyle Navbar keeping in mind that many new headings will be coming up in the future.

**Comment by sayan011** [comment]
Can I work on this **issue**?

**Comment by Jassi10000** [comment]
@swapnilsparsh  Can I too partner with @sayan011 and work on this issue under GSSOC'22

**Comment by swapnilsparsh** [comment]
> 

Appreciate your interest but 1 assignee at a time if @sayan011 is not able to complete it then you can work till then look after some issues. 
Good Luck 👍🏻

**Comment by swapnilsparsh** [comment]
> Can I please work on this **issue**?

Update ?

**Comment by sayan011** [comment]
I'm adding some cool Hover effects and remodeling it totally .Actually my end sem exams are going on,so I got a little bit busy with that but I hope I can finish it before saturday.

**Comment by mayank-del** [comment]
@swapnilsparsh  sir, check , i have created a new cool ui for nabar

**Comment by navyasharma0203** [comment]
Can I work on this issue..if it isn't closed yet??

**Comment by mayank-del** [comment]
> Can I work on this issue..if it isn't closed yet??

You should wait, i have created a PR .He is doing some work , so please wait untill my pr merged

**Comment by ghimanshi** [comment]
Can I work on this?

**Comment by swapnilsparsh** [comment]
> Can I work on this?

Yes

**Comment by Riya14-dangra** [comment]
Can you please assign me this issue under kwoc2022??

**Comment by MaYaNkKashyap681** [comment]
can I work on this? If it is still open.

**Comment by codemaniac-sahil** [comment]
Hey @swapnilsparsh , can I work on this issue.

**Comment by SwastikNanda** [comment]
@swapnilsparsh Sir, I would like to work on this issue under IWOC program, if you allow it.

**Comment by codemaniac-sahil** [comment]
@swapnilsparsh, may I know what you want me add the functionality. Right now I am thinking of making navbar to stick on the top as it will look great from my perspective.

**Comment by Ayush-2301** [comment]
Hey @swapnilsparsh I would like to work on this issue . Though the Navbar already look good but some changes are need , like good animation , is active states, scroll effect for navbar . If this nobody is working on this can you please assign this to me

**Comment by swapnilsparsh** [comment]
#169 Resolved by @Ayush-2301
