### ISSUE TITLE
Implement interaction

### ISSUE THREAD

**Issue by swapnilsparsh** [swapnilsparsh/DevEmpire#108]
![Screenshot 2022-03-01 132436](https://user-images.githubusercontent.com/69387608/156127885-6fa2a9e8-2a9e-42a3-9a3a-ca2e75a85f59.png)

Implement interaction in this SVG or replace it with your innovative idea

**Comment by Rituresh143** [comment]
i am open do work on this problem under Gssoc22 please assign to me

**Comment by Rituresh143** [comment]
we can discuss the problem??

**Comment by swapnilsparsh** [comment]
> we can discuss the problem??

Yes, sure
What problem are you facing?

**Comment by Rituresh143** [comment]
what actually need to change the SVG photo or any other thing

**Comment by mayank-del** [comment]
Can I work under this issue under gssoc22?
