### ISSUE TITLE
Sticky Navbar and it changes colour when scrolled down the page

### ISSUE THREAD

**Issue by SayantaniDeb** [swapnilsparsh/DevEmpire#11]
Please assign this task to me.

**Comment by swapnilsparsh** [comment]
> Please assign this task to me.

When Scroll down it should have a glassmorphism effect.

**Comment by swapnilsparsh** [comment]
@SayantaniDeb Any updates? 🙂

**Comment by SayantaniDeb** [comment]
I will create the PR by tomorrow. 😅

**Comment by SayantaniDeb** [comment]
Hey, I'm closing this issue as i'm having some problem with the glassmorphism effect.
