### ISSUE TITLE
Add new Open Source Programs data

### ISSUE THREAD

**Issue by swapnilsparsh** [swapnilsparsh/DevEmpire#111]
Before Making a PR

1. Don't message in the issue for assigning this issue, open a new issue stating your `PROGRAM` which you want to add.

2. Edit only in [Programs-Data.js](https://github.com/swapnilsparsh/DevEmpire/blob/master/components/programs/Programs-Data.js) file 
3. Attach a proper image in the [programs-img](https://github.com/swapnilsparsh/DevEmpire/tree/master/public/assets/programs-img) folder with a proper name.
4. Give a proper description of the Program data that you are adding.

**Comment by ShwetKhatri2001** [comment]
Hi @swapnilsparsh 
I'd like to work on this issue. I'm GSSOC22 participant.

**Comment by swapnilsparsh** [comment]
> Hi @swapnilsparsh I'd like to work on this issue. I'm GSSOC22 participant.
Open a new Issue stating the program you want to add.
