### ISSUE TITLE
Add  MLH Fellowship Program 

### ISSUE THREAD

**Issue by aryasoni98** [swapnilsparsh/DevEmpire#114]
![MLH-Fellowship](https://user-images.githubusercontent.com/18515597/157381663-34f1248b-5927-4948-8837-51f09bccd758.png)

Major League Hacking (MLH) is a global community for student developers. MLH recently launched a program known as MLH fellowship which is a 12-week remote program where students collaborate on Open Source projects that align their personal interests with the general requirements of the industry and students can participate from their homes.

**Comment by swapnilsparsh** [comment]
@aryasoni98 It is already there on the website.
