### ISSUE TITLE
Add Open Mainframe Project Mentorship Program

### ISSUE THREAD

**Issue by aryasoni98** [swapnilsparsh/DevEmpire#116]
Open Mainframe Project also has its own open-source program and the mentees will be able to expand their knowledge on the mainframe technology.

**Comment by swapnilsparsh** [comment]
> 

Provide more details under which section you will be adding it.

**Comment by swapnilsparsh** [comment]
> Open Mainframe Project also has its own open-source program and the mentees will be able to expand their knowledge on the mainframe technology.

Provide more details under which section you will be adding it.

**Comment by aryasoni98** [comment]
Open Mainframe Project Mentorship Program, mentees will be able to….

- Expand their knowledge of mainframe technology
- Help contribute to open source projects that will make it easier for these infrastructure applications to run on mainframe.
- Learn crucial skills for a intern to be successful in a technology role within today’s enterprise, including but not limited to project planning, communication, problem solving, and scoping.
- Be exposed to potential employers which help them transition into their career path successfully.
