### ISSUE TITLE
Replace all the current SVG

### ISSUE THREAD

**Issue by swapnilsparsh** [swapnilsparsh/DevEmpire#135]
Replace all the SVG with some interactive animations or lottie or maybe something else, but keep it related to color code which is there in [CONTRIBUTING.md](https://github.com/swapnilsparsh/DevEmpire/blob/master/CONTRIBUTING.md)

**Comment by sristis0202** [comment]
Is this issue still available? If yes then I would like to work on it for SSOC'22.

**Comment by swapnilsparsh** [comment]
> Is this issue still available? If yes then I would like to work on it for SSOC'22.

Go ahead

**Comment by cout-sid** [comment]
I would like to work on this. Can you assign it to me under kwoc ?

**Comment by cout-sid** [comment]
hey do I also have to change the svg in navigation bar and footer?

**Comment by swapnilsparsh** [comment]
> hey do I also have to change the svg in navigation bar and footer?

No, only the landing page SVG

**Comment by SwastikNanda** [comment]
@swapnilsparsh Sir, I would like  to work on this issue under IWOC.
