### ISSUE TITLE
Implement Dark mode

### ISSUE THREAD

**Issue by swapnilsparsh** [swapnilsparsh/DevEmpire#136]
All the color details has been added to [CONTRIBUTING.md](https://github.com/swapnilsparsh/DevEmpire/blob/master/CONTRIBUTING.md)

Take the idea from this [figma file](https://www.figma.com/file/x2Uer8vvMorWCtyyFCanYd/DevEmpire-(Bloo-Lo-Fi)?node-id=259%3A0)

**Comment by OmkarGeedh** [comment]
I would like to contribute to this issue!

**Comment by swapnilsparsh** [comment]
> I would like to contribute to this issue!

God Luck 👍🏻

**Comment by thisisharsh7** [comment]
@swapnilsparsh  As a hacktoberfest participant, I would like to contribute to this issue. If it is undone, please assign it to me.

**Comment by iks1** [comment]
Can i work on it ?

**Comment by Yash-Raj-50** [comment]
Can I work on this? I want to do this for kwoc end evals.

**Comment by swapnilsparsh** [comment]
> Can I work on this? I want to do this for kwoc end evals.

Start the work.
