### ISSUE TITLE
Games Page Image

### ISSUE THREAD

**Issue by swapnilsparsh** [swapnilsparsh/DevEmpire#137]
Games data has already been added. So you have to work on the following things:
1. VIsit every website which is there in [Games-data.js](https://github.com/swapnilsparsh/DevEmpire/blob/master/components/games/Games-Data.js)
2. Take a screenshot or google and take image for the website.
3. Add images [here](https://github.com/swapnilsparsh/DevEmpire/tree/master/public/assets/games-img) 
4. Remove the JS Toolkit from Navbar and replace it with Games
5. Do the same for the routing of games.

**Comment by ayushshaw90** [comment]
Shall I do this part?

**Comment by ayushshaw90** [comment]
https://betterwebtype.com/triangle/
This link of Better Web Type Triangle shows authorized error. 

https://vim-adventures.com/
This link of Vim Adventures does not open.

There are two entries for crunch zilla, shall I remove one of them

Shall I remove these entry from  Games-Data.js file.

**Comment by swapnilsparsh** [comment]
> https://betterwebtype.com/triangle/
> This link of Better Web Type Triangle shows authorized error. 
> 
> https://vim-adventures.com/
> This link of Vim Adventures does not open.
> 
> There are two entries for crunch zilla, shall I remove one of them
> 
> Shall I remove these entry from  Games-Data.js file.
> 
> 

Fix the links accordingly and replace the images with the new ones you are adding.

**Comment by bradydavenport** [comment]
Hello, I'd like to work on this

**Comment by ayushshaw90** [comment]
I have resolved the issue and created a pull request.
