### ISSUE TITLE
Missing links in navbar 

### ISSUE THREAD

**Issue by Yash-Raj-50** [swapnilsparsh/DevEmpire#153]
Link to the js-toolkits page is missing in the expanded navbar, while the link to the games page is missing in the navbar for small screens.

![image](https://user-images.githubusercontent.com/80768955/209566908-64137770-4d62-4759-adfd-d99c518a8db0.png)
![image](https://user-images.githubusercontent.com/80768955/209566931-bc172757-0181-4e9f-994e-b9e3c1e5e770.png)

**Comment by Yash-Raj-50** [comment]
Can maintainers confirm this bug? I would like to fix this issue.

**Comment by swapnilsparsh** [comment]
Remove the JS toolkits and add Games in place of it.
Fix the landing page JS toolkit name also

**Comment by Yash-Raj-50** [comment]
>Fix the landing page JS toolkit name also

So do I need to remove this js-toolkit section on the landing page??

**Comment by Yash-Raj-50** [comment]
> Fix the landing page JS toolkit name also

So do I need to remove/replace this section from landing page?
![image](https://user-images.githubusercontent.com/80768955/209672174-83ac8a25-d577-47ad-8755-086fe9f6745e.png)

**Comment by swapnilsparsh** [comment]
> > Fix the landing page JS toolkit name also
> 
> So do I need to remove/replace this section from landing page?
> ![image](https://user-images.githubusercontent.com/80768955/209672174-83ac8a25-d577-47ad-8755-086fe9f6745e.png)
> 

Yes, also find the suitable SVG for the same color design.
