### ISSUE TITLE
Add new event

### ISSUE THREAD

**Issue by Koustavjr** [swapnilsparsh/DevEmpire#156]
**Is your feature request related to a problem? Please describe.** I would like to add new event.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Koustavjr** [comment]
@swapnilsparsh can u please assign me this issue under kwoc

**Comment by swapnilsparsh** [comment]
Which event?

**Comment by Koustavjr** [comment]
> Which event?

Open Source event by IIIT Kalyani .
