### ISSUE TITLE
NavBar content overflow on different view port Issue

### ISSUE THREAD

**Issue by iemprashant** [swapnilsparsh/DevEmpire#158]
**Describe the bug**
NavBar content overflow on different viewport Issue

**To Reproduce**
1. Resize the window size from mobile to desktop.
2. At Approx 760px width, overflow can be seen.

**Expected behavior**
No Overflow at any screen size

**Screenshots**

![Screenshot from 2023-02-04 14-54-38](https://user-images.githubusercontent.com/53941491/216759757-2613c73e-119d-4b43-b0de-15121ce2801f.png)

**Comment by swapnilsparsh** [comment]
@iemprashant NIce, fix this bug and look out for more.
