### ISSUE TITLE
UI Enhancement in Navbar.

### ISSUE THREAD

**Issue by iemprashant** [swapnilsparsh/DevEmpire#159]
**Is your feature request related to a problem? Please describe.**
No, it is just good to have.

**Describe the solution you'd like**
- A smooth Navbar opening and closing in mobile view.
- Unable to Access the Cancel button using Tab when Navbar is open in Mobile.
- Focus Trapping in Navbar, When Navbar is open.

**Comment by swapnilsparsh** [comment]
Start the work on this.

**Comment by iemprashant** [comment]
Hey, I was exploring the project and found some issues so contributed to reporting.
Please assign it to someone other.
