### ISSUE TITLE
Router is not working when reloading the any page

### ISSUE THREAD

**Issue by meinhoonharsh** [swapnilsparsh/DevEmpire#16]
**Describe the bug**
When you visit on any route other than "/" it will be working fine, but as soon as you refresh the Page, It produces an Error
And also If you directly visit any other route, you get the Same Error

**To Reproduce**
- First Way
  - Go to https://devempire.netlify.app/
  - Click on ambassador or any other link in the Navbar except home
  - Refresh the Page
 - Second Way
   - Directly go to https://devempire.netlify.app/ambassador
  
**Expected behavior**
When you refresh that page or directly visit the route, It must be serving the content properly

**Screenshots**
![image](https://user-images.githubusercontent.com/64343449/135532072-cc6e2ae8-72c9-411c-a3c6-1dc0f640e5f3.png)

**Comment by tnmyk** [comment]
I know how to solve this! Please assign it to me!

**Comment by tnmyk** [comment]
I ll look into it. Please assign it to me

**Comment by meinhoonharsh** [comment]
@tnmyk Yeah, you will not get these Issue in React Development Server
