### ISSUE TITLE
Improve the Dark UI

### ISSUE THREAD

**Issue by swapnilsparsh** [swapnilsparsh/DevEmpire#161]

**Comment by ksh1710** [comment]
hey @swapnilsparsh can u please assign this issue to me under iwoc'23

**Comment by Bharadwajshivam28** [comment]
assign to me sir @swapnilsparsh

**Comment by Bharadwajshivam28** [comment]
and elaborate the issue @swapnilsparsh

**Comment by Bharadwajshivam28** [comment]
and drop the things that you want to be improved like the keywords

**Comment by swapnilsparsh** [comment]
@Bharadwajshivam28 You are already assigned with issues, finish them off and then get assign on new issues.

**Comment by Bharadwajshivam28** [comment]
ok sir

**Comment by elidakirigo** [comment]
hello!, I'd love to work on this issue if it's still open and un-assigned. thanks

**Comment by elidakirigo** [comment]
recieved.

**Comment by elidakirigo** [comment]
recieved.

**Comment by swapnilsparsh** [comment]
@elidakirigo What's the update ?

**Comment by elidakirigo** [comment]
not yet, I've had pending projects i had to finish, I'm gonna go through tommorow and give an update

**Comment by elidakirigo** [comment]
> @elidakirigo What's the update?

@swapnilsparsh not yet, I've had pending projects i had to finish, I'm gonna go through tommorow and give an update

**Comment by Bharadwajshivam28** [comment]
@swapnilsparsh Assign to me sir not under event just i want to fix it

**Comment by elidakirigo** [comment]
> @elidakirigo Update ?

So sorry , not yet

**Comment by elidakirigo** [comment]
I've changed the toggle button CSS to suit the container, and I've also changed the background color of the back-to-top, I've noticed the SCSS isn't rendered by next and I think it would be a good idea if it did.
