### ISSUE TITLE
Footer changes with Dark mode toggle button

### ISSUE THREAD

**Issue by swapnilsparsh** [swapnilsparsh/DevEmpire#162]
It should follow the current UI/UX and color code

**Comment by ksh1710** [comment]
hey @swapnilsparsh can u please assign this issue to me under IWOC'23

**Comment by iamatifmoin** [comment]
@swapnilsparsh Please assign this issue to me next.

**Comment by Bharadwajshivam28** [comment]
@swapnilsparsh assign to me sir as no one is active i can fix it

**Comment by Bharadwajshivam28** [comment]
and currently it has one footer so the data in that footer will be same in new one also right ? i have to create new footer

**Comment by Bharadwajshivam28** [comment]
![Screenshot from 2023-02-27 11-57-06](https://user-images.githubusercontent.com/108119109/221490562-ea1606ea-bb34-49c0-81b4-21198253e102.png)

**Comment by Bharadwajshivam28** [comment]
currently this is footer so these will be also in new footer right?

**Comment by Bharadwajshivam28** [comment]
i have build it sir

**Comment by swapnilsparsh** [comment]
@Bharadwajshivam28 You are already assigned with issues, finish them off and then get assign on new issues.

**Comment by Bharadwajshivam28** [comment]
ok sir

**Comment by Ayush-2301** [comment]
@swapnilsparsh I would like to work on this issue , but can you provide some description , for example what content you want in footer.

**Comment by swapnilsparsh** [comment]
@Ayush-2301 Content will be same, or you can emphasie your own creativity and make a more professional footer rather than a SVG/Fancy footer which is right now

**Comment by Bharadwajshivam28** [comment]
@swapnilsparsh   I want to build it , not under any event but i want to fix it

**Comment by swapnilsparsh** [comment]
Share the design before starting the work ?

> @swapnilsparsh I want to build it , not under any event but i want to fix it

**Comment by Bharadwajshivam28** [comment]
> Share the design before starting the work ?
> 
> > @swapnilsparsh I want to build it , not under any event but i want to fix it
> 
> 

Ok

**Comment by naitik-lodha** [comment]
@swapnilsparsh can you please assign this issue to me under GSSOC'23?

**Comment by swapnilsparsh** [comment]
@naitik-lodha Will be sharing the design super soon

**Comment by naitik-lodha** [comment]
Do I have to make the design?

**Comment by swapnilsparsh** [comment]
Few change that you have to do which are not in the photo
1. Use DevEmpire blue crown instead of yellow crown
2. Gap between two support and explore columns is quite large, reduce it accordingly 
3. Don use that black background, use the footer background which is blue

![image](https://github.com/swapnilsparsh/DevEmpire/assets/69387608/b5f24b47-b1bf-4c9d-9141-04915d7667f5)

**Comment by swapnilsparsh** [comment]
@naitik-lodha I have updated the issue as you will be moving the dark mode toggle to fotter according to design. Mark the issue as hard.

**Comment by naitik-lodha** [comment]
Can you please send the Figma file for the design?

**Comment by naitik-lodha** [comment]
How should the footer look for mobile?

**Comment by swapnilsparsh** [comment]
> How should the footer look for mobile?

That you have to make it work out on your own 🙂

**Comment by naitik-lodha** [comment]
Sorry I won't be able to do it.

**Comment by tanish111** [comment]
can you please assign this issue to me under GSSOC'23?

**Comment by Soumyajit2825** [comment]
@swapnilsparsh can u assign me under this issue??
I think the dark mode toggle button is fine in the left bottom

**Comment by swapnilsparsh** [comment]
> @swapnilsparsh can u assign me under this issue??
> I think the dark mode toggle button is fine in the left bottom

I have already mentioned a photo above about the changes that have to be done . I have assigned you for the same.

**Comment by Soumyajit2825** [comment]
@swapnilsparsh I have created the footer as your recommendation and as your given style 
I am attaching the screen-shots of my changes 
Please let me know if some changes needed.

![Screenshot 2023-05-27 201107](https://github.com/swapnilsparsh/DevEmpire/assets/100519291/e9076a56-e79d-4df2-a40e-ae6a85c68d39)

**Comment by swapnilsparsh** [comment]
@Soumyajit2825 Great work 😍, make a PR for the same.
