### ISSUE TITLE
Page Number at below

### ISSUE THREAD

**Issue by swapnilsparsh** [swapnilsparsh/DevEmpire#163]
By default is should show only 16-20 cards then there should be page number below to go to next page to see more cards but page should not reload only component should refresh.

**Comment by Ayush-2301** [comment]
hey @swapnilsparsh, I would like to work on this issue can you assign this to me .

**Comment by Ayush-2301** [comment]
1: ![image](https://user-images.githubusercontent.com/114101923/219033204-51b9557e-f6c9-480a-b9bc-0fee67ad1785.png)
2: ![image](https://user-images.githubusercontent.com/114101923/219033436-d8f5a186-81f4-4439-b6d1-be034d392adc.png)
hey @swapnilsparsh can you  choose one of these layout for pagination , also where should i add this component right next to label section or bottom of the page or on both sides

**Comment by Ayush-2301** [comment]
and one more thing I limited the no of cards to show on one page to 16 , is it fine or should I reduce it to 12

**Comment by swapnilsparsh** [comment]
Resolved by @Ayush-2301
