### ISSUE TITLE
Adding a free web dev tool

### ISSUE THREAD

**Issue by Swastik1710** [swapnilsparsh/DevEmpire#17]
**Is your feature request related to a problem? Please describe.**
Adding animated illustrations to a website makes it look a lot more beautiful. But animating it on your own isn't that easy. Moreover, adding GIF or MP4 videos make the website heavy and thus slow.

**Describe the solution you'd like**
There's a website called [LottieFiles](https://lottiefiles.com/) which provides awesome animated illustrations in the form of json files which are lightweight and easy to implement. You can either use a link to the file or even download the json file and add it to your project folder. There are a lot of cool animations available free of cost. Also if we want, we can edit the illustrations as per our need and downloaded the updated json file. 
Thus I would like to add this to the web dev tools as illustrations is in huge demand now a days.

**Describe alternatives you've considered**

**Additional context**
![1](https://user-images.githubusercontent.com/71871571/135558514-27c7bfc3-be2d-46fa-b744-8a711ab81dc1.png)

**Comment by swapnilsparsh** [comment]
@Swastik1710 Wonderful idea 🤯
Can you describe a little more, where you will be using this on the website?

**Comment by Swastik1710** [comment]
Hey @swapnilsparsh, firstly we can replace all the illustrations used on the website with these.
And secondly, we can add this to the list of web dev tools.

**Comment by swapnilsparsh** [comment]
> Hey @swapnilsparsh, firstly we can replace all the illustrations used on the website with these. And secondly, we can add this to the list of web dev tools.

Ok, when you will change the illustration to Lottie, all the Lootie should not look in different colors or designs.
Keep the color code the same as the website and all the Lottie should be likely the same to each other.
Best of Luck 👍🏼

**Comment by swapnilsparsh** [comment]
Issue resolved by @Swastik1710 #34
