### ISSUE TITLE
Make new Landing Page

### ISSUE THREAD

**Issue by swapnilsparsh** [swapnilsparsh/DevEmpire#170]
1. Use some interactive animtions or illustrations
2. Keep the color scheme same

**Comment by swapnilsparsh** [comment]
> I would like to work on this but could you please give me a graphic design?

There is no graphic desgin, you have to arrange it by your own and then share the designs here. After finalising the design you can continue on implementing it.

**Comment by Bharadwajshivam28** [comment]
@swapnilsparsh I want to make it sir

**Comment by swapnilsparsh** [comment]
> @swapnilsparsh I want to make it sir

Share the design first.

**Comment by Bharadwajshivam28** [comment]
> > @swapnilsparsh I want to make it sir
> 
> Share the design first.

Ok

**Comment by Pranjal7852** [comment]
Can you please assign me this issue, I would love to make a new design on Figma

**Comment by swapnilsparsh** [comment]
@Pranjal7852 Will be sharing the design super soon, working on it from a quite long time.

**Comment by swapnilsparsh** [comment]
@Pranjal7852 due to lack of time, it is incomplete, please co operate with the design which is there below.
1. On the right side of "bigger and better" there will be cards going up and down automatically which from all over the website which can be amassador, progrms, etc..
2. The black photo which is there adjust is according to the blue theme.
3. for now add lorem ipsum in testimonial.

![image](https://github.com/swapnilsparsh/DevEmpire/assets/69387608/039e68ac-16ea-4061-b89f-459c8b44f480)

**Comment by Pranjal7852** [comment]
sure i will get the work going
1. Can you please provide some clear image of the following design
2. I didn't understand what is the purpose of the black image please elaborate

**Comment by Pranjal7852** [comment]
ok on it

**Comment by swapnilsparsh** [comment]
@Pranjal7852 any updates ?

**Comment by Pranjal7852** [comment]
Just working on final changes 
Will make a pr by tonight

**Comment by swapnilsparsh** [comment]
@Pranjal7852 Any update ?

**Comment by devmusiczz** [comment]
@swapnilsparsh I want to work on this issue. I can make your website landing page more interactive as well as creative. Please assign this issue to me.

**Comment by devmusiczz** [comment]
Current Landing Page
![Screenshot (35)](https://github.com/swapnilsparsh/DevEmpire/assets/114563397/14c09cf2-256f-4323-8e1e-02f03a02b5ef)
New Landing Page
![Screenshot (36)](https://github.com/swapnilsparsh/DevEmpire/assets/114563397/c33267a5-eb42-4125-ae00-557ddb8a8e75)
@swapnilsparsh Please Review the changes

**Comment by devmusiczz** [comment]
@swapnilsparsh Please Review
Current
![Screenshot (39)](https://github.com/swapnilsparsh/DevEmpire/assets/114563397/67aba65c-51a1-4450-8b51-1c59ed15d521)
New
![Screenshot (37)](https://github.com/swapnilsparsh/DevEmpire/assets/114563397/bf0255b1-ab76-4260-9ce1-312c600f3053)
![Screenshot (36)](https://github.com/swapnilsparsh/DevEmpire/assets/114563397/cacab364-9597-4599-aaaa-72e2f6c4538e)

**Comment by swapnilsparsh** [comment]
@devmusiczz Looking great 😍 but it will look more better if you follow the current color theme that you can find [here](https://github.com/swapnilsparsh/DevEmpire/blob/master/CONTRIBUTING.md#color-codes-)
