### ISSUE TITLE
Navbar isn't collapse automatically after somebody click on the nav-element (on Mobile-Screen) 

### ISSUE THREAD

**Issue by Lobi29** [swapnilsparsh/DevEmpire#175]
![1](https://github.com/swapnilsparsh/DevEmpire/assets/108052802/8c2ac47a-1c95-4eed-bc00-5725dd22fc4c)

### ISSUE:
**On Mobile size devices, After clicking on the nav element, Navbar isn't collapse automatically, making the first view of the desired page smaller**

### SOLUTION:
**I will make some changes the JS and SASS file such that after clicking on the nav element, navbar will automatically collapse down**

Please assign this issue to me, under @GSSOC

**Comment by rhithesh** [comment]
hi I will  be working on this thanks.

**Comment by rhithesh** [comment]
hi its fixed 

https://github.com/swapnilsparsh/DevEmpire/assets/115660976/095872bc-1b8b-41e4-8989-e47c0de79501
