### ISSUE TITLE
Adding animations to buttons

### ISSUE THREAD

**Issue by Indira-kumar** [swapnilsparsh/DevEmpire#176]
Description:
Currently, the buttons on our website lack interactivity, leading to a static user experience.

Screenshots:
![image](https://github.com/swapnilsparsh/DevEmpire/assets/74497486/b43f46f9-7412-41d8-bb47-9ffcf181434b)

Expected Outcome:
By adding animations to buttons, we can enhance the interactivity on our website, resulting in a more engaging and interactive user experience

**Comment by Indira-kumar** [comment]
@swapnilsparsh 
Please assign me this issue under GSSOC'23. I would like to work on it.

**Comment by silwite** [comment]
Hello can you assign this to me under GSSOC'23.
Teach Stack- MERN stack

**Comment by swapnilsparsh** [comment]
@Indira-kumar Good Luck and you have to add animation to every button which is there on whole website, not only one.

**Comment by Indira-kumar** [comment]
Yeah sure, will do that.
Thanks for assigning me :)

**Comment by swapnilsparsh** [comment]
@Indira-kumar I want this animation on button, also keep in mind the [color code ](https://github.com/swapnilsparsh/DevEmpire/blob/master/CONTRIBUTING.md#color-codes-)

https://codepen.io/aaroniker/full/XWYpyNM

**Comment by swapnilsparsh** [comment]
@Indira-kumar Any updates ?

**Comment by Indira-kumar** [comment]
hey @swapnilsparsh sorry for the delay, caught up with academic works, I will make the PR in two days time.

**Comment by Indira-kumar** [comment]
sorry for the delay, I made the changes, but was trying to make the above expected animation with the least amount of changes in the codebase. Will make the PR within today no matter what.
