### ISSUE TITLE
Add eligibility criteria

### ISSUE THREAD

**Issue by KhushiTayal** [swapnilsparsh/DevEmpire#177]
**Is your feature request related to a problem? Please describe.**
Write who is eligible to participate in the given program in a short and concise way so that it will be easy for the user to apply.

**Describe the solution you'd like**
Add this eligibility criterion to the card of every program.

**Comment by KhushiTayal** [comment]
@swapnilsparsh may you please assign this issue to me under GSSOC'23

**Comment by swapnilsparsh** [comment]
@KhushiTayal Where you will be doing this in the card ??

![image](https://github.com/swapnilsparsh/DevEmpire/assets/69387608/8726eb60-24ef-4a34-9daf-b2dd6dee94a8)

**Comment by KhushiTayal** [comment]
Just below the program description in thr card.

**Comment by swapnilsparsh** [comment]
@KhushiTayal Not needed as of now as we are chaning a design of cards, when you click on "VIew More" button then a modal will open containing all that information.

**Comment by KhushiTayal** [comment]
@swapnilsparsh Great idea! May I work on adding a modal  when you click on "VIew More" button?

**Comment by swapnilsparsh** [comment]
@KhushiTayal I have created a new issue regarding ths and assigned you.👍
