### ISSUE TITLE
Mention timeline of the program

### ISSUE THREAD

**Issue by KhushiTayal** [swapnilsparsh/DevEmpire#178]
**Is your feature request related to a problem? Please describe.**
Mention the time of the year when that program is organized every year.

**Describe the solution you'd like**
Write a timeline represented by the month when that program is organized in the card.
example: Oct-Dec

**Comment by KhushiTayal** [comment]
@swapnilsparsh may you please assign this issue to me under GSSOC'23

**Comment by swapnilsparsh** [comment]
@KhushiTayal Great idea but timeline changes eveytime according to program manager so it is not fixed.
