### ISSUE TITLE
Shift Github, Product Hunt and Twitter links to the footer section

### ISSUE THREAD

**Issue by KhushiTayal** [swapnilsparsh/DevEmpire#179]
Shift Github, Product Hunt and Twitter links to the footer section from top of page for better UI

![image](https://github.com/swapnilsparsh/DevEmpire/assets/82832128/eb351793-e8f3-4c6d-9ecd-30f3d98da8ff)

Please assign this issue to me under GSSoC'23

**Comment by swapnilsparsh** [comment]
@KhushiTayal Will be sharing a new design soon, as of now no need of this.
