### ISSUE TITLE
Adding some more Open Source Programs

### ISSUE THREAD

**Issue by Swastik1710** [swapnilsparsh/DevEmpire#18]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
I've myself participated in these Open Source Programs
Here are they :
DevScript Winter Of Code [(DWOC)](https://devscript.org/woc/)
25th December - 25th February
DevIncept Contribution Program [(DCP)](https://contribute.devincept.com/)
10th July - 9th August

I would like to add these two to the list.
**Describe alternatives you've considered**

**Additional context**
![1](https://user-images.githubusercontent.com/71871571/135560120-3386e895-d3b5-4f5d-813b-dbbd1307ae64.png)
![2](https://user-images.githubusercontent.com/71871571/135560113-5f93fdf9-040f-4dd7-9ce6-b21280e75992.png)

**Comment by swapnilsparsh** [comment]
@Swastik1710 I am assigning this issue to you. Please open the PR for these two programs with proper images and details.

**Comment by Swastik1710** [comment]
Sure @swapnilsparsh.
Thanks for assigning.
Shall I make 2 separate PRs for the two programs?

**Comment by swapnilsparsh** [comment]
> Sure @swapnilsparsh. Thanks for assigning. Shall I make 2 separate PRs for the two programs?

If possible make it 1 PR else you can make 2 PR.

**Comment by swapnilsparsh** [comment]
Issue resolved by @Swastik1710 #33
