### ISSUE TITLE
Adding animations on the web page

### ISSUE THREAD

**Issue by abhinav-m22** [swapnilsparsh/DevEmpire#180]
By adding animations on the web page to different sections, UX can be improved.
I would like to work on building this feature.

Please assign me the issue under GSSoC'23.

**Comment by swapnilsparsh** [comment]
@abhinav-m22 Which page are you referring to ?

**Comment by abhinav-m22** [comment]
> @abhinav-m22 Which page are you referring to ?

I am talking about the Home Page. Like adding fade-in or fade-out animations to different sections such as "Ambassador", "Programs", "Web Dev Tools", "Games", etc.

**Comment by swapnilsparsh** [comment]
@abhinav-m22  leave Homepage, work on individual pages

**Comment by abhinav-m22** [comment]
> @abhinav-m22 leave Homepage, work on individual pages

Okay... I'll add the animations like hover transitions on the card components of individual pages.

**Comment by swapnilsparsh** [comment]
@abhinav-m22 Add the animation which is there on the cards of this website both on dark and light mode https://chronark.com/projects

**Comment by dhrumishah** [comment]
> @abhinav-m22 Add the animation which is there on the cards of this website both on dark and light mode https://chronark.com/projects

Hey what's the update on this issue? I would like to work on this

**Comment by abhinav-m22** [comment]
> > @abhinav-m22 Add the animation which is there on the cards of this website both on dark and light mode https://chronark.com/projects
> 
> Hey what's the update on this issue? I would like to work on this

I've started working and almost completed it. Some small changes are remaining.. I'll make a PR by today evening.
Please try to find other issues or features.

**Comment by abhinav-m22** [comment]
I've made a PR - #205 
Please have a look..

**Comment by swapnilsparsh** [comment]
@abhinav-m22 any updates ?
