### ISSUE TITLE
[Bug] : Improve styling of the button 

### ISSUE THREAD

**Issue by Tushar98644** [swapnilsparsh/DevEmpire#182]
<img width="1440" alt="Screenshot 2023-05-21 at 3 39 04 PM" src="https://github.com/swapnilsparsh/DevEmpire/assets/107763774/34b226d7-56e0-4a3c-bab8-77b1d07e56aa">

The above-marked button kind of mixes in with the bg..I can improve the styling of the button to match the overall design

**Comment by Abhinavcode13** [comment]
Please assign this to me @swapnilsparsh

**Comment by pritamjoardar** [comment]
I'm interested in working on it. Please assign it to me @swapnilsparsh

**Comment by swapnilsparsh** [comment]
@Tushar98644 is already working on it
