### ISSUE TITLE
Search doesn't function properly when not on 1st Page.

### ISSUE THREAD

**Issue by JawHawk** [swapnilsparsh/DevEmpire#185]
**Describe the bug**
The search functions properly on 1st Page. For example, 
![image](https://github.com/swapnilsparsh/DevEmpire/assets/86140365/96177af1-8841-4744-83ab-843b212d6372)
But if the same search is done on 2nd or further pages, search is expected to give same results or wrt page data, but it doesn't.
![image](https://github.com/swapnilsparsh/DevEmpire/assets/86140365/8992e8fd-6a18-468c-b285-4ba7482fe799)

**To Reproduce**
1. Go to Ambassadors section.
2. Search something in the Search bar, for eg aleo. It works as in Image 1.
3. Now remove the search and go down, click on page 2 or any further page.
4. Then again search the same, but it will not function properly.

**Expected behavior**
The search should happend globally on all available data. So the result should be same irrespective of any page. Also even if the search may be wrt page data, then too it doesn't search properly.

**Screenshots**
Snips are attached above.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Brave

**Comment by swapnilsparsh** [comment]
@JawHawk In page1 the search you are using is for that particular page, in 2nd page the search is there for that particular page

For global search you can use the navbar search.

**Comment by JawHawk** [comment]
@swapnilsparsh 
Even that doesn't work i.e for particular page. For eg cudos Rangers is on 2nd page of Ambassador section. But if I search for it on the same page i.e 2nd, it shows no results.
![image](https://github.com/swapnilsparsh/DevEmpire/assets/86140365/a45fbbaf-282b-4968-a174-3fbe2186e065)
![image](https://github.com/swapnilsparsh/DevEmpire/assets/86140365/fb6b63d6-8872-4118-86b9-fe51f796235e)

Pls try it once.

**Comment by swapnilsparsh** [comment]
@JawHawk It is working in mine, can you record a video and share it here

![image](https://github.com/swapnilsparsh/DevEmpire/assets/69387608/e309ab3f-6217-41f7-a0ab-adcf27b2be1f)

**Comment by JawHawk** [comment]
@swapnilsparsh Here it is :

https://github.com/swapnilsparsh/DevEmpire/assets/86140365/c91819b3-8e25-44c7-a00e-bfbbf5ca89b9

**Comment by swapnilsparsh** [comment]
@JawHawk So the issue is if you are on ambasaador page and you have open page number 2 then if you will dont get results of other page number.
