### ISSUE TITLE
Implement pagination in search results

### ISSUE THREAD

**Issue by swapnilsparsh** [swapnilsparsh/DevEmpire#188]
When you use global search which is there in navbar then show only 12 results , if there are more then show pagination accordingly.

![image](https://github.com/swapnilsparsh/DevEmpire/assets/69387608/9340e121-2212-4248-ba62-3639d84196f7)

**Comment by salted0dreams** [comment]
I would like to work on this issue. Can you please assign it to me? @swapnilsparsh

**Comment by Laxmankohar** [comment]
Hey @swapnilsparsh  , I would like to work on this issue under GSSoc23. Can you assign it to me?

**Comment by Arka2708** [comment]
I would like to work on this issue under GSSoC'23

**Comment by Laxmankohar** [comment]
https://github.com/swapnilsparsh/DevEmpire/assets/73365025/85a5a100-eee1-423e-80d2-746ad2d10e50

@swapnilsparsh bro, According to you, when  searching something it is showing only 12 results but when i search it is showing all the results , you can see it above in the video. only thing is that we have to scroll down , there is no pagination.

**Comment by swapnilsparsh** [comment]
@Laxmankohar That is the issue only, you have to implement pagination on the search results, if there are cards more than 12 then you have to show pagination .

**Comment by swapnilsparsh** [comment]
@Laxmankohar any updates ?

**Comment by Laxmankohar** [comment]
> @Laxmankohar any updates ?

yes, i am working. There is a issue when i click on the pagination no, it gets redirect to homepage. Once i will fix that i will make a PR.

**Comment by Michelle031** [comment]
@Laxmankohar  do you need help?
