### ISSUE TITLE
ADD hover feature to cards

### ISSUE THREAD

**Issue by Abhinavcode13** [swapnilsparsh/DevEmpire#189]
**Describe the solution you'd like**

![image](https://github.com/swapnilsparsh/DevEmpire/assets/126642111/92cff5be-fbc8-41da-a582-55e3339ad8d3)
To improve the user experience, I want to add a hover feature to the cards. please assign this issue to me @swapnilsparsh under gssoc 23

thanks and regards
Abhinav Kumar

**Comment by swapnilsparsh** [comment]
There is already an issue opened [here](https://github.com/swapnilsparsh/DevEmpire/issues/180)
