### ISSUE TITLE
Removing underline from headings and adding some hover effects

### ISSUE THREAD

**Issue by mohittk** [swapnilsparsh/DevEmpire#19]
The underline on words of headings doesn'nt look good according to UX perspective, So I'm removing it. In addition to it, I'm adding particle js.

**Comment by swapnilsparsh** [comment]
> The underline on words of headings doesn'nt look good according to UX perspective, So I'm removing it. In addition to it, I'm adding particle js.

If you will remove the underline, how come users will know that it is a link or just a heading?
Assigning this issue to you, please look after it.

**Comment by swapnilsparsh** [comment]
Issue resolved by #20
