### ISSUE TITLE
Make website descriptions more action oriented

### ISSUE THREAD

**Issue by poorvijn** [swapnilsparsh/DevEmpire#190]
Hello, I went through the website and I felt that it would be great if we could have the descriptions more action-oriented.

For example, rather than saying " Here you can find all resources and details of Open Source Programs", we could say "Looking for Open Source programs/resources? Find them right here!". Similarly for other descriptions.

I feel it would make it more energetic and exciting!

If this sounds like a good idea, could you please assign this issue to me under GSSoC'23?

**Comment by poorvijn** [comment]
Hello, I've prepared the descriptions and I'd love to get some feedback before actually changing them.

Introduction:

It's time to close those extra tabs. Welcome to your one-stop solution for all resources and details on ambassador/fellowship programs, open source programs, web dev tools and so much more! 

Ambassador:
Don't miss the deadline. Apply to ambassador/fellowship programs from all over the world right here, right now.

Open source:
Looking for an open-source program to apply to? You're just a click away. Find all details right here! 

Games text
Ever heard of 'All work and no play makes the developer dull' ? Here's your chance to mix some play into your work !

**Comment by swapnilsparsh** [comment]
> Hello, I've prepared the descriptions and I'd love to get some feedback before actually changing them.
> 
> Introduction:
> 
> It's time to close those extra tabs. Welcome to your one-stop solution for all resources and details on ambassador/fellowship programs, open source programs, web dev tools and so much more! 
> 
> Ambassador:
> Don't miss the deadline. Apply to ambassador/fellowship programs from all over the world right here, right now.
> 
> Open source:
> Looking for an open-source program to apply to? You're just a click away. Find all details right here! 
> 
> Games:
> Ever heard of 'All work and no play makes the developer dull' ? Here's your chance to mix some play into your work !

Nice just change this line "ambassador/fellowship" to something else also you have to change for web/dev alsom

**Comment by poorvijn** [comment]
Does this sound better?

Ambassador:
Find the perfect program for you from 75+ ambassador and fellowship programs from all over the world
 
Web development text
Power up your website with awesome tools from CSS generators and stock photos, to icons, illustrations, vectors and so much more, all at one place

**Comment by swapnilsparsh** [comment]
@poorvijn good to go 👍🏻

**Comment by poorvijn** [comment]
Awesome, I've raised a PR for the same!
