### ISSUE TITLE
Want to change the UI of the navbar on mobile size devices without effecting the design of the larger size devices

### ISSUE THREAD

**Issue by Lobi29** [swapnilsparsh/DevEmpire#192]
### **ISSUE :** 
![1](https://github.com/swapnilsparsh/DevEmpire/assets/108052802/31879760-6ca1-4a2f-a828-880142dc6bca)

### **SOLUTION :** 
![6](https://github.com/swapnilsparsh/DevEmpire/assets/108052802/ee5d2729-b925-492e-92bc-b57858a367d7)

I will change the UI by simply making some changes on the CSS and JSX file

Please assign this issue to me, under @GSSOC2023

**Comment by swapnilsparsh** [comment]
Not needed
