### ISSUE TITLE
Feature Request: Want to add the zooming effect in the Card.JS on Hover for Better UI experience

### ISSUE THREAD

**Issue by Preetam078** [swapnilsparsh/DevEmpire#195]
I want to add the hover zooming effect to the card.js to make the UI more enhanced 

![Screenshot from 2023-05-22 21-03-36](https://github.com/swapnilsparsh/DevEmpire/assets/81969353/09d6a62c-c47f-40ec-a5a4-41ea4133176f)

I will adding some CSS to the file to make it possible 
please assign this task to me under the GSSOC 2023

**Comment by swapnilsparsh** [comment]
Not needed as someone is already working on enhancing the UI of card.
