### ISSUE TITLE
Improve Searching Ability

### ISSUE THREAD

**Issue by RashakDude** [swapnilsparsh/DevEmpire#196]
**Is your feature request related to a problem? Please describe.**
Yes, I would like to propose that search ability is only on heading and not the data. Would like to add searching on the basis of information too.

**Describe the solution you'd like**
Solution is simple, add searching ability on basis of information too with the text highlighted.

Please assign me the issue @swapnilsparsh

**Comment by swapnilsparsh** [comment]
@RashakDude Great idea 👍

**Comment by swapnilsparsh** [comment]
@RashakDude any update ?

**Comment by RashakDude** [comment]
@swapnilsparsh Done with the filter part, working on highlight text part. Will update by first half of the day.
