### ISSUE TITLE
GSSoC '23 | Addition of Web Dev Tool

### ISSUE THREAD

**Issue by YashkShrivas4491** [swapnilsparsh/DevEmpire#201]
I'm in GSSoC

I want to add a web dev tool under the web dev section which is CSSPeeper.

![image](https://github.com/swapnilsparsh/DevEmpire/assets/87111197/eb797475-269f-4d5f-ba8a-d55e9e637712)

could you assign me this issue @swapnilsparsh

**Comment by swapnilsparsh** [comment]
@YashkShrivas4491 Great finding but only for 1 I can't assign you level 1 label.
Try to find atleast 1 in every category.

**Comment by YashkShrivas4491** [comment]
> @YashkShrivas4491 Great finding but only for 1 I can't assign you level 1 label. Try to find atleast 1 in every category.

Ok

**Comment by YashkShrivas4491** [comment]
>1 . I want to add a web dev tool under the web dev section which is CSSPeeper.
> 
> ![image](https://user-images.githubusercontent.com/87111197/240129822-eb797475-269f-4d5f-ba8a-d55e9e637712.png)
> 
> could you assign me this issue @swapnilsparsh

  2. Under Games Section
 link :- https://screeps.com/
![image](https://github.com/swapnilsparsh/DevEmpire/assets/87111197/2883db1f-88f3-47ec-aa9e-25a14c84f473)

 3. Intel Student Ambassador Program
 
![image](https://github.com/swapnilsparsh/DevEmpire/assets/87111197/31d9e564-6c8d-4105-ae09-09ee510cf311)


now can you Assign me this issue @swapnilsparsh
