### ISSUE TITLE
Adding attractive hover animation on every card in the website

### ISSUE THREAD

**Issue by prrockzed** [swapnilsparsh/DevEmpire#209]
**Is your feature request related to a problem? Please describe.**
I would like to add attractive hover animation to the cards on the website and not just normal hover effects like zooming in etc.

**Describe the solution you'd like**

https://github.com/swapnilsparsh/DevEmpire/assets/97661506/bd998609-efcd-4ff9-9b71-904507ea6d5c

I will add colors to the animations as well.

**Additional context**
@swapnilsparsh Please assign this feature to me under GSSoC'23.

**Comment by swapnilsparsh** [comment]
There is already an issue opened regarding this
