### ISSUE TITLE
Modal on every card

### ISSUE THREAD

**Issue by swapnilsparsh** [swapnilsparsh/DevEmpire#210]
Adding a modal when you click on "VIew More" button?

**Comment by prrockzed** [comment]
Hi @swapnilsparsh , I would like to work on this issue. Please assign this to me under gssoc23.

**Comment by KhushiTayal** [comment]
@swapnilsparsh please assign this issue to me.

**Comment by swapnilsparsh** [comment]
@prrockzed It was @KhushiTayal who pointed this issue in another issue so I have assigned her.

**Comment by swapnilsparsh** [comment]
@KhushiTayal there will be two button now in every card, one will be "View More" and other will be "VIsit Website" as shown belown in the image

![image](https://github.com/swapnilsparsh/DevEmpire/assets/69387608/6359754d-ca64-4c06-af3a-8e63e40f89a0)

**Comment by prrockzed** [comment]
> @prrockzed It was @KhushiTayal who pointed this issue in another issue so I have assigned her.

OK👍

**Comment by KhushiTayal** [comment]
@swapnilsparsh I have implemented "View More" and "Visit Website" buttons as suggested by you. 
I also implemented a sample Modal. When user clicks on "View More" button a Modal appears which looks like the image given below,
![image](https://github.com/swapnilsparsh/DevEmpire/assets/82832128/b3318a66-8636-484d-b9e5-63f3a9e48f57)

Please suggest what sections should I add in Modal.

**Comment by swapnilsparsh** [comment]
> @swapnilsparsh I have implemented "View More" and "Visit Website" buttons as suggested by you. 
> I also implemented a sample Modal. When user clicks on "View More" button a Modal appears which looks like the image given below,
> ![image](https://github.com/swapnilsparsh/DevEmpire/assets/82832128/b3318a66-8636-484d-b9e5-63f3a9e48f57)
> 
> Please suggest what sections should I add in Modal.
> I have used head, link, image, alt, about parameters to display this information but how can we add further more information which is not present in Ambassador-Data.js file, as manually adding information won't be a good idea.

Remove the close button instead of placing a cross button at the top right corner. Add more details regarding the program with proper heading and make it mobile responsive also.

**Comment by mukul314** [comment]
Hello @swapnilsparsh , I saw that there are three issues which are open for grabbing since @Laxmankohar wants to do this issue, can you divide the issues #210 and #246 between me and laxamn? 
We will be working on sepearte issues which are open for grab.

**Comment by swapnilsparsh** [comment]
@mukul314 Sure, so I have assigned #210 to @Laxmankohar and #246 to @mukul314 👍

**Comment by mukul314** [comment]
Hey @swapnilsparsh is the below arrangements of buttons okay?

<img width="222" alt="2023-06-06 19_46_52-DevEmpire - Brave" src="https://github.com/swapnilsparsh/DevEmpire/assets/76463001/b0eef435-fc21-4285-9bd3-bd486537f178">

**Comment by swapnilsparsh** [comment]
@mukul314  looking great 👍🏻

**Comment by mukul314** [comment]
Hello @swapnilsparsh !!
I have the modal and the links ready, the main question that I want to ask is from where will we fetch the extra information about all the cards, typing that manually will be a tedious task. Do you have any suggestions on that?

**Comment by swapnilsparsh** [comment]
> Hello @swapnilsparsh !! I have the modal and the links ready, the main question that I want to ask is from where will we fetch the extra information about all the cards, typing that manually will be a tedious task. Do you have any suggestions on that?

As of now we have to do manually only because I am working on the API , so when the API will be ready then all the data will be fetched from API.

**Comment by swapnilsparsh** [comment]
> 

Also include a gap or margin between two buttons.

**Comment by swapnilsparsh** [comment]
> Hey @swapnilsparsh is the below arrangements of buttons okay?
> 
> <img alt="2023-06-06 19_46_52-DevEmpire - Brave" width="222" src="https://user-images.githubusercontent.com/76463001/243904022-b0eef435-fc21-4285-9bd3-bd486537f178.png">

Also include a gap or margin between two buttons.

**Comment by xmayukx** [comment]
Hey @swapnilsparsh can i work on this issue? I think pull this off in a more elegant way.

**Comment by mukul314** [comment]
> @mukul314 Any updates ?

Hey @swapnilsparsh , I got busy with some other stuff so couldn't focus on this task, sorry for the delay !
If @xmayukx is ready then he can go for it !

**Comment by xmayukx** [comment]
@swapnilsparsh Could you please assign this issue to me?

**Comment by swapnilsparsh** [comment]
@xmayukx Assigned you 👍
