### ISSUE TITLE
Landing Page Flicker 

### ISSUE THREAD

**Issue by JawHawk** [swapnilsparsh/DevEmpire#213]
**Describe the bug**
Whenever user opens the website, there is an unnecessary flicker of Landing Page which is due to incorrect loading state management. This needs to be removed to get a production level code & performance.

**To Reproduce**
1. Open the https://devempire.netlify.app/ in new Tab
2. Before the loading icon, you can see the flicker.

**Expected behavior**
Whenever the site is opened, the loading icon should smoothly appear rather than a flicker.

**Video**

https://github.com/swapnilsparsh/DevEmpire/assets/86140365/bfb86a90-cc9d-4503-bf8c-5a0700ec6c72

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Brave

**Additional context**
Also the codebase is somewhat less structured . For eg there is usage of both class and functional components, repetition of code etc.

**Comment by fernanda-freitas** [comment]
Hey @JawHawk, I'd like to work on that, can you pleas assign the issue to me?

**Comment by JawHawk** [comment]
@fernanda-freitas , @swapnilsparsh is the maintainer of codebase, also I created the issue so that I can be assigned to work on this.

**Comment by fernanda-freitas** [comment]
Oh sorry, I was already looking into the codebase. Wish a good work to you on the issue :)

**Comment by JawHawk** [comment]
Np Thanks !!

**Comment by swapnilsparsh** [comment]
@JawHawk great finding.
