### ISSUE TITLE
Add Web Dev Tools

### ISSUE THREAD

**Issue by Sriparno08** [swapnilsparsh/DevEmpire#216]
I want to add Shutterstock, a popular tool that helps people use stock photos in their projects at no cost.

I would like to contribute it as part of GSSoC'23.

**Comment by Sriparno08** [comment]
Here you go, @swapnilsparsh:

Illustration: Ouch
Icons: IconScout
Vectors/Svg: SVG Repo
Colors: Coolors
CSS: Animista
Stock Photos: Shutterstock

**Comment by swapnilsparsh** [comment]
> Here you go, @swapnilsparsh:
> 
> Illustration: Ouch
> Icons: IconScout
> Vectors/Svg: SVG Repo
> Colors: Coolors
> CSS: Animista
> Stock Photos: Shutterstock

Cross check on the website whether it is already there or not if not then open a PR for the same.

**Comment by Sriparno08** [comment]
Yeah @swapnilsparsh, I have checked the website and haven't found any of them.

Can I now go ahead and make a contribution as part of GSSoC'23?

**Comment by swapnilsparsh** [comment]
> Yeah @swapnilsparsh, I have checked the website and haven't found any of them.
> 
> Can I now go ahead and make a contribution as part of GSSoC'23?

@Sriparno08 go ahead and make a PR

**Comment by Sriparno08** [comment]
Okay 👍
