### ISSUE TITLE
[GSSoC'23] Add footer with proper information and about section

### ISSUE THREAD

**Issue by Aditya-Khaladkar** [swapnilsparsh/DevEmpire#220]
**Is your feature request related to a problem? Please describe.**
There's no proper footer in this website, when the user is visiting he/she is not able to get the information about this website 

**Describe the solution you'd like**
I can improve the design of footer with proper and more information and add a about page so that user can know more about this website

can you assign this issue under GSSoC'23 ?

**Comment by swapnilsparsh** [comment]
There is already an issue opened for this
