### ISSUE TITLE
Add Events such as hackathons in the programmes tab 

### ISSUE THREAD

**Issue by Shaurya10101** [swapnilsparsh/DevEmpire#224]
**Is your feature request related to a problem? Please describe.**
Rather than just Open source programmes events like web3 cloud events and hackathons (online ones too) can be added 

**Describe the solution you'd like**
More number of cards that display more events like DTU NSUT or online hackathons

**Describe alternatives you've considered**

**Additional context**
![image](https://github.com/swapnilsparsh/DevEmpire/assets/118044473/33fec1e1-1866-4ad4-86dc-dba550db9670)

**Comment by swapnilsparsh** [comment]
@Shaurya10101 Can you share some examples.
