### ISSUE TITLE
[Add]: Adding the LFX Mentorship Program in the 'Programs' Section.

### ISSUE THREAD

**Issue by Ayan-M-Dev** [swapnilsparsh/DevEmpire#227]
### Objective
Adding an Open Source Program known as "LFX Mentorship" in the 'Programs' Section 
### Screenshots
![Screenshot 2023-05-27 150729](https://github.com/swapnilsparsh/DevEmpire/assets/101629997/73c8c98b-6702-45b7-9f6c-52723a089760)
_This is the section where the program will be added_ 

![Screenshot 2023-05-27 150151](https://github.com/swapnilsparsh/DevEmpire/assets/101629997/3f378632-b506-4363-b6a2-2a2721b7a9d5)
_This where the user will be redirected after browsing and clicking the view more button ie the 'LFX Mentorship Website'_

Just for Reference :-
"LFN mentorship" and "LFX mentorship" are different mentorship programs. LFN (Linux Foundation Networking) and LFX (Linux Foundation Exchange) are both initiatives by the Linux Foundation, but they focus on different areas within the open source community.

LFN mentorship typically refers to mentorship programs and opportunities provided by the Linux Foundation Networking projects and communities. It is aimed at individuals interested in networking technologies and projects supported by LFN.

On the other hand, LFX mentorship refers to mentorship programs offered by the Linux Foundation Exchange. LFX provides mentorship opportunities across a wide range of open source projects and technologies, covering various domains beyond networking.

While both programs involve mentorship, they are associated with different organizations and communities, and their specific focus areas may vary.

**Comment by Ayan-M-Dev** [comment]
**I would like to work on this issue. Please assign me the issue.**
[GSSoC Contributor]

**Comment by swapnilsparsh** [comment]
@Ayan-M-Dev Add at least 5 open source programs

**Comment by Ayan-M-Dev** [comment]
@swapnilsparsh  Currently I have one, Can I work on one for now?

**Comment by swapnilsparsh** [comment]
You can work , but then it won't be counting as a GSSoC contribution. @Ayan-M-Dev

**Comment by Ayan-M-Dev** [comment]
A contribution is a contribution, doesn't matter if it won't be counting but I would be happy if it was :) @swapnilsparsh
