### ISSUE TITLE
Fix footer

### ISSUE THREAD

**Issue by swapnilsparsh** [swapnilsparsh/DevEmpire#230]
There are problems in the responsiveness of the footer.

**Comment by Laxmankohar** [comment]
Hey @swapnilsparsh , I would like to work on this issue. Can you assign it to me?

**Comment by Web403** [comment]
Hello @swapnilsparsh and @Laxmankohar , I would love to work together on this issue.

**Comment by swapnilsparsh** [comment]
@Laxmankohar Update ?

**Comment by Laxmankohar** [comment]
> @Laxmankohar Update ?

Yes, i am working. Today evening i will make a PR.
