### ISSUE TITLE
[Bug] : Navbar does not persist on scrolling down

### ISSUE THREAD

**Issue by rayyan016** [swapnilsparsh/DevEmpire#231]
**Description** :
While scrolling down, the ideal practice is to have the navbar persist on the screen the whole duration. [For reference](https://www.google.com/chrome/). Currently, it does not appear when scrolled down.

**Screenshots**

![dev emp issue1](https://github.com/swapnilsparsh/DevEmpire/assets/102043379/eee583c2-7eba-4173-b3d6-530a7563d5c3)

**Desktop :**
 - OS: Windows 11
 - Browser Chrome

If the change is wanted, do assign this to me under GsSOC'23. Thankyou.

**Comment by jstevenat** [comment]
Hi, can I get this assigned to me?

**Comment by swapnilsparsh** [comment]
@rayyan016 go ahead 🚀
