### ISSUE TITLE
[Feature] : Dark/Light mode toggle on Navbar

### ISSUE THREAD

**Issue by rayyan016** [swapnilsparsh/DevEmpire#232]
**Problem:**
The button to toggle dark/light mode is situated in the footer which can only be accessed if the user scrolls all the way down. There should instead be an option to have the toggle available easily, preferably on the navbar.

![dev emp issue2](https://github.com/swapnilsparsh/DevEmpire/assets/102043379/522973fb-b336-435d-92c1-068bbad12871)

**Solution**
I would like to add the option to add the toggle button to the navbar. To the right of **games** and left of **search**
I would not remove the button from the footer since it was there before (If wanted, can remove. Do suggest.)

**Additional reference**
For reference, I am taking inspiration from navbar of [bootstrap website](https://getbootstrap.com/)

**Comment by swapnilsparsh** [comment]
Not needed
