### ISSUE TITLE
Add box shadows to card

### ISSUE THREAD

**Issue by Riy-a** [swapnilsparsh/DevEmpire#246]
Hey @swapnilsparsh,

I would like to add a box shadow on every card when the user hovers over the particular card. It will enhance the User Experience.

<img width="1080" alt="Screenshot 2023-06-01 at 1 04 42 PM" src="https://github.com/swapnilsparsh/DevEmpire/assets/78693959/bcf99b31-25a0-421d-a293-2b6458aabcbf">

Please assign this issue to me under Gssoc tag.

**Comment by swapnilsparsh** [comment]
@Riy-a You have to add this effect on every card which is there on this website -> https://chronark.com/projects

**Comment by Laxmankohar** [comment]
@swapnilsparsh , i would like to work on this issue under gssoc. Can i assign it to me?

**Comment by swapnilsparsh** [comment]
@Laxmankohar Any updates ?

**Comment by abhinav-m22** [comment]
@swapnilsparsh Any update on this issue?
I would like to work on it if it is not done yet

**Comment by abhinav-m22** [comment]
Hey @swapnilsparsh What type of styles are needed for the cards?
I had an idea to use the translate property of CSS to provide a hover effect to the cards.
It will make it look it a 3D animation, the component will move from its x and y positions and appear slightly bumped!

Or any different styling is required?

**Comment by swapnilsparsh** [comment]
> Hey @swapnilsparsh What type of styles are needed for the cards? I had an idea to use the translate property of CSS to provide a hover effect to the cards. It will make it look it a 3D animation, the component will move from its x and y positions and appear slightly bumped!
> 
> Or any different styling is required?

I need this type of animaition -> https://chronark.com/projects

**Comment by Prajwal0225** [comment]
Currently, no one is assigned to this issue I would like to work on this issue..

@swapnilsparsh can you please assign this issue to me? So, that I start woking on this issue.
