### ISSUE TITLE
Add new resource for open- source programs 

### ISSUE THREAD

**Issue by jayasridharmireddi** [swapnilsparsh/DevEmpire#247]
In the open-source programs, I want to add **Bitcoin Summer of Code** which is a very good program for students, and graduates. 
I am a GSSoC'23 contributor, please assign me this issue.

**Comment by swapnilsparsh** [comment]
Add more programs and tools in other category @jayasridharmireddi

**Comment by jayasridharmireddi** [comment]
Sure, I will.

**Comment by swapnilsparsh** [comment]
@jayasridharmireddi Sorry to say but In order to earn a level tag, contributors must make significant contributions to the project. This could include adding new features, fixing bugs, or improving documentation.

**Comment by jayasridharmireddi** [comment]
So, I shouldn't work on this anymore?

**Comment by swapnilsparsh** [comment]
> So, I shouldn't work on this anymore?

No, please have a look at other issues
