### ISSUE TITLE
[BUG] Global search box closes automatically on clicking anywhwere due to which links are not accessible.

### ISSUE THREAD

**Issue by Sar-thak-3** [swapnilsparsh/DevEmpire#249]
**Describe the bug**
During a global search on the website, when clicked anywhere else the search input box automatically closes and the user can't select any shown results. The reference to the issue is shown in the below video.

**Expected behavior**
The input box will close only when there is no text inside it. If there is text inside then it should not close.

**Video**
https://github.com/swapnilsparsh/DevEmpire/assets/100359818/5a655f50-43dd-4234-a0bc-06d6f0b8b446

**Comment by swapnilsparsh** [comment]
@Sar-thak-3 Nice finding ⭐

**Comment by rhithesh** [comment]
@Sar-thak-3  @swapnilsparsh  can i also work on this?

**Comment by kaleemullah786** [comment]
hey this seems interesting. can i work on it

**Comment by Sar-thak-3** [comment]
@swapnilsparsh Kindly assign me the issue under GSSoC 23!
