### ISSUE TITLE
Adding Hover Effect on Ambassador card

### ISSUE THREAD

**Issue by Hemant2335** [swapnilsparsh/DevEmpire#256]
**Is your feature request related to a problem? Please describe.**
The cards don't have any effects when hovering on it .

**Describe the solution you'd like**
I can 
-> Add a  mouse cursor styling
-> Scaling on hover with smooth transition

**Describe alternatives you've considered**
Other could be popping out the details on the card on hover

**Comment by swapnilsparsh** [comment]
@Hemant2335 There is an issue already opened for this
