### ISSUE TITLE
Add description under respective pages (UX)

### ISSUE THREAD

**Issue by udz-codes** [swapnilsparsh/DevEmpire#26]
Just to improve User Experience, I would like to work on this and add a description of each page under the title. If you have any suggestions like reducing the width or anything, just let me know. I am ready to work on this.

Example:

![image](https://user-images.githubusercontent.com/21984964/135712972-a30d7ed2-9661-4094-bc27-370cb9f39cf7.png)

**Comment by swapnilsparsh** [comment]
> Just to improve User Experience, I would like to work on this and add a description of each page under the title. If you have any suggestions like reducing the width or anything, just let me know. I am ready to work on this.
> 
> Example:
> 
> ![image](https://user-images.githubusercontent.com/21984964/135712972-a30d7ed2-9661-4094-bc27-370cb9f39cf7.png)

Enhance the UX 😍
