### ISSUE TITLE
docs: update contributing guidelines

### ISSUE THREAD

**Issue by Anmol-Baranwal** [swapnilsparsh/DevEmpire#261]
- There is no guidelines to add a resource in the contributing guidelines, so I want to update this.
- I am experienced with all the terms, so I will add the changes with proper conventions and guidelines.

> I will be doing this contribution as part of GSSoC'23.

Please assign me, and I will start contributing towards this issue.

**Comment by swapnilsparsh** [comment]
Soon we wll be adding the API so there is no need of this

**Comment by Anmol-Baranwal** [comment]
> Soon we wll be adding the API so there is no need of this

If you know how to do this, please mention it and pin the issue so that others don't waste time on it. However, I can only make a request for this.
