### ISSUE TITLE
docs: update PR Template

### ISSUE THREAD

**Issue by Anmol-Baranwal** [swapnilsparsh/DevEmpire#262]
- These detailed explanations should be added as comments, and it lacks basic information for first-time contributors. Kindly assign me this issue.

- I will make the necessary updates to the template to ensure structured pull requests, which will ultimately facilitate the review process.

> I will be doing this contribution under GSSoC'23.

> Image
![image](https://github.com/swapnilsparsh/DevEmpire/assets/74038190/4258377c-13da-41e4-9b15-b325b4373ec3)

Please assign me, and I will start contributing towards this issue.

**Comment by swapnilsparsh** [comment]
Not needed

**Comment by Anmol-Baranwal** [comment]
> Not needed

Sure. Thanks for letting me know.
