### ISSUE TITLE
Feature: Add new web development tool

### ISSUE THREAD

**Issue by Mahitej28** [swapnilsparsh/DevEmpire#263]
Hello!
I am Mahima Churi, a proud contributor at GSSoc'23.
I would like to work on this project by adding a new open-source web development tool, that would help users creating simplified illustrations.

If you think it is legit then do assign me the issue under GSSoC '23 with the level of the PR as well..!

**Comment by swapnilsparsh** [comment]
@Mahitej28 Just adding one tool will not grant you any level tag, if you wish to contribute outisde of gssoc then you are free to open a PR direcly without opening a issue. Thank You 🚀
