### ISSUE TITLE
[Feat]: Add save button

### ISSUE THREAD

**Issue by suzy-g38** [swapnilsparsh/DevEmpire#266]
**Is your feature request related to a problem? Please describe.**

There are many topics like ambassadors, programs, webdev and games . It will be great if we can save them for later.

**Describe the solution you'd like**

We will use a save button and on clicking on the button t will be saved for you. As there is no backend by far I would like to use localstorage to store them.

**Describe alternatives you've considered**

**Additional context**

I would like to work on it under GSSOC'23.

**Comment by swapnilsparsh** [comment]
@suzy-g38 Great idea but soon we will be implementing the backend so we are already working on this feature. Very soon it will be live.
