### ISSUE TITLE
Navbar Improvement 

### ISSUE THREAD

**Issue by 9520prashant** [swapnilsparsh/DevEmpire#267]
Hey @swapnilsparsh I have Improved the navbar in which i added the background transparent feature You can see the demo below :

https://github.com/swapnilsparsh/DevEmpire/assets/99237795/6518539c-27ab-44f2-9688-0f3fc2ca4691

If It loos fine then kindly assign me this issue under GSSOC.

**Comment by swapnilsparsh** [comment]
@9520prashant Great idea but as you can see when the video end then the navbar contents are not readable due to transparent effect. Try for some different apporach and open a issue if found any. 👍
