### ISSUE TITLE
Adding logos to the social links in the footer

### ISSUE THREAD

**Issue by mukul314** [swapnilsparsh/DevEmpire#268]
**Is your feature request related to a problem? Please describe.**
 I think we must add logos of the respective links beside them, this will make the footer more eye-catchy.

**Describe the solution you'd like**
We can add logos and also add hover and scaling effects on them.

**Additional context**
I'd like to work on this under GSSOC'23 if you approve @swapnilsparsh .

**Comment by swapnilsparsh** [comment]
@mukul314 Not needed
