### ISSUE TITLE
Add new web tools and games

### ISSUE THREAD

**Issue by Abhinavcode13** [swapnilsparsh/DevEmpire#269]
please assign me this issue @swapnilsparsh under gssoc 23

thanks

**Comment by swapnilsparsh** [comment]
@Abhinavcode13 Sorry to say but In order to earn a level tag, contributors must make significant contributions to the project. This could include adding new features, fixing bugs, or improving documentation.

**Comment by Abhinavcode13** [comment]
@swapnilsparsh any level 1 or level 2 issue which can be worked upon? let me know

**Comment by swapnilsparsh** [comment]
@Abhinavcode13 Yes there are issues opened on which you can work, or you can open your own issues if found any on tht website
