### ISSUE TITLE
Enhancing of navbar in mobile view

### ISSUE THREAD

**Issue by mukul314** [swapnilsparsh/DevEmpire#270]
**Is your feature request related to a problem? Please describe.**
Currently the the navbar in the mobile view just opens rapidly and the hamburger's transition is also not smooth, I'd like to add a smooth transition to the navbar as well as hamburger in the mobile view.

**Describe the solution you'd like**
This will make the website more appealing, just a view changes in the nav component and the corresponding CSS or SCSS file.

See the below video for more context:

https://github.com/swapnilsparsh/DevEmpire/assets/76463001/c6716702-23e4-4325-86e8-8c4bcb0e5662

Something like this maybe?

**Additional context**
@swapnilsparsh , I'd like to work on this for GSSOC'23.

**Comment by swapnilsparsh** [comment]
@mukul314 I will be making a new issue regarding the Navbar,as we are going to change the whole design.
