### ISSUE TITLE
Footer link issue

### ISSUE THREAD

**Issue by swapnilsparsh** [swapnilsparsh/DevEmpire#271]
When clicking on these links then page should not reload, only the component should updated 

![image](https://github.com/swapnilsparsh/DevEmpire/assets/69387608/b4fa7258-ce31-42ae-8cd7-92f0dc5f9fe0)

**Comment by jpelinski** [comment]
It looks that footer is using just simple Styled Link component, 
` <FooterLink href="/ambassador">Ambasaddor</FooterLink>`
I belive using 
`import Link from "next/link"`
like in navbar would solve the problem. I could work on that tomorrow if you still need help with that.

**Comment by sagnik-p** [comment]
This issue has been inactive for a long time
I would like to work on this issue
Please assign
