### ISSUE TITLE
Make the website smooth

### ISSUE THREAD

**Issue by swapnilsparsh** [swapnilsparsh/DevEmpire#272]
While you use the website then you might feel like the website is laggy or not smooth so you have to work on it and remove any unnecessary thing that maybe causing this issue.

**Comment by Sejal1411** [comment]
Hey @swapnilsparsh I would like to work in this issue...could you please assign this issue to me.

**Comment by xmayukx** [comment]
Hey @swapnilsparsh I would love to work on this issue could you please assign it to me?

**Comment by swapnilsparsh** [comment]
@Sejal1411 Any updates ?

**Comment by Kushagra102** [comment]
Hey @swapnilsparsh can you please assign this issue to me. I will try to resolve this issue using some optimisation techniques.
