### ISSUE TITLE
Addition of SITEMAP for seo

### ISSUE THREAD

**Issue by mukul314** [swapnilsparsh/DevEmpire#274]
Currently there is no site map for the website, having a sitemap is essential for the website. For example, Google largely finds webpages through links. And if the site is brand new and only has a handful external backlinks, then a sitemap is HUGE for helping Google find pages on your site.

I will use a normal XML sitemap in the webiste that will boost it's seo performance.

@swapnilsparsh what do you think about this?

**Comment by swapnilsparsh** [comment]
@mukul314 Go ahead 👍🏻
