### ISSUE TITLE
Add a SVG with text if the user didn't get anything in return while searching in all the pages.

### ISSUE THREAD

**Issue by swapnilsparsh** [swapnilsparsh/DevEmpire#28]
![Annotation 2021-10-02 185136](https://user-images.githubusercontent.com/69387608/135718149-5083ebc9-6870-4daa-a41d-1ea846fc6bb4.png)

**Comment by Johnisaig** [comment]
Hi Sir @swapnilsparsh, I would like to work on this, could you assign it to me?

**Comment by Johnisaig** [comment]
Hi Sir @swapnilsparsh, Please review my PR #32.

Here's the sample web view

![web-view-noresults](https://user-images.githubusercontent.com/45925383/135726879-44d25ccf-e748-4071-9600-a44ef5adea22.png)

Here's the mobile view
![noresult-mobile](https://user-images.githubusercontent.com/45925383/135726889-40efcfa7-3b8b-4357-b20f-c5e5917330c5.png)

**Comment by swapnilsparsh** [comment]
Issue resolved by @Johnisaig #32
