### ISSUE TITLE
Move the dark mode button

### ISSUE THREAD

**Issue by kaashikaagrawal** [swapnilsparsh/DevEmpire#280]
**Describe the bug**
Currently the dark mode button is present at the bottom of the page. It should be present at the top for the user's convenience.

**To Reproduce**
1. Go to the website
2. Scroll all the way down
3. The button is present at the lower left corner

**Expected behavior**
Instead of the user having to scroll down to find the button, it should be clearly visible near the top of the landing page.

**Screenshots**
<img width="960" alt="image" src="https://github.com/swapnilsparsh/DevEmpire/assets/97745349/6facea54-241e-4deb-af2b-cc9948f0cd3b">

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Comment by Kushagra102** [comment]
Hey @swapnilsparsh I would Like to work on this issue under gssoc'23. Please assign it to me.
