### ISSUE TITLE
Adding Typewriter effect in the main heading

### ISSUE THREAD

**Issue by Anshika-Jain02** [swapnilsparsh/DevEmpire#283]
*We can add a typewriter effect in the below heading to give a dynamic effect and to improve the visual appearance of the overall website.*

![dev empires](https://github.com/swapnilsparsh/DevEmpire/assets/104912087/cfee1db0-01fe-441f-b8af-40c911f7a651)

@swapnilsparsh Please assign me this issue under gssoc'23

**Comment by swapnilsparsh** [comment]
@Anshika-Jain02 Not needed as of now
