### ISSUE TITLE
[Feature]: add dependabot

### ISSUE THREAD

**Issue by harmeetsingh11** [swapnilsparsh/DevEmpire#291]
### Is your feature request related to a problem? Please describe.
Keeping the project's dependencies up to date can be a challenging task, if its done manually.

### Describe the solution you'd like
We need to add Dependabot as it helps us to keep our dependencies up to date. Once, Dependabot will be activated, it will start submitting PRs with any outdated dependency based on package.json file.

### Record
- [x] I agree to follow this project's Code of Conduct
- [x] I'm a GSSoC'23 contributor
- [x] I want to work on this issue

Please assign me this issue under gssoc23.
Thanks

**Comment by swapnilsparsh** [comment]
@harmeetsingh11 Not needed as of now
