### ISSUE TITLE
Add the campus ambassador program of Zuno/Foundit

### ISSUE THREAD

**Issue by Parmesh119** [swapnilsparsh/DevEmpire#292]
You have to add the campus ambassador program that is happing for every university and this campus ambassador program is of Zuno/Foundit that are very famous.

**Comment by Parmesh119** [comment]
I am working on this issue.

**Comment by swapnilsparsh** [comment]
@Parmesh119 Sorry to say but In order to earn a level tag, contributors must make significant contributions to the project. This could include adding new features, fixing bugs, or improving documentation.
