### ISSUE TITLE
Enhance Ui of the Ambassador page.

### ISSUE THREAD

**Issue by Pragati-3003** [swapnilsparsh/DevEmpire#294]
I would like to change the ui of the ambassador  page by adding some cool effects and also would like to change the ui of the cards too.
So,please assign this to me under Gssoc'23.
![Screenshot 2023-06-20 142233](https://github.com/swapnilsparsh/DevEmpire/assets/132778037/96235a2f-f307-4b38-a604-5114bdf0e177)

**Comment by swapnilsparsh** [comment]
@Pragati-3003 Ok, can you share some deisgns before implementing them, also keep in view the Color Scheme.

**Comment by Pragati-3003** [comment]
> @Pragati-3003 Ok, can you share some deisgns before implementing them, also keep in view the Color Scheme.

Okie..
