### ISSUE TITLE
Host the Website on a custom Domain Name

### ISSUE THREAD

**Issue by dineshkumardavanam** [swapnilsparsh/DevEmpire#295]
This is a great Looking website, But It would be better if It would be hosted on a custom Domain name
https://www.godaddy.com/en-in/domainsearch/find?itc=dlp_domain&domainToCheck=devempire&tmskey=1dom_03_buydomain

Just check It out here, You are getting a Domain for Very less rates for the first Year, If you like you can Buy the domain and Give it to me, I will host and Give it to you

This Contribution is under GSSOC 23

**Comment by swapnilsparsh** [comment]
@dineshkumardavanam Already purchased a domain, soon we will be hosting

**Comment by dineshkumardavanam** [comment]
Okay @swapnilsparsh
