### ISSUE TITLE
The navlinks of the Navbar on the mobile view is not showing up 

### ISSUE THREAD

**Issue by vishnubansal001** [swapnilsparsh/DevEmpire#297]
**Describe the bug**
The bug us that in the mobile view when on clicking the hamburgers icon the navbar's navlinks or the components are not being rendered on the screen. 

I am a GsSOC'23 contributor 
Please allow me to resolve this issue 
i want to work on this please allow me @swapnilsparsh

**Comment by swapnilsparsh** [comment]
@vishnubansal001 It is working fine, share a video if you are facing any issue.
