### ISSUE TITLE
Ui of the footer section in the mobile view 

### ISSUE THREAD

**Issue by vishnubansal001** [swapnilsparsh/DevEmpire#298]
I want to make a complete responsive and user interactive footer for the website please allow me to do so as you can that it is not in the attached screenshot by me 

![Screenshot (125)](https://github.com/swapnilsparsh/DevEmpire/assets/101445306/eb77e0ff-966d-43ec-a8a8-22cbfb1257b8)

I am a GsSOC'23 contributor 
please allow me to contribute this part
I want to resolve this issue please allow me @swapnilsparsh

**Comment by swapnilsparsh** [comment]
@vishnubansal001 It is responsive for mobile screens, might be you are checking on very small screens which are not used anymore.
