### ISSUE TITLE
Add the new program of DevNetwork Advisory Board

### ISSUE THREAD

**Issue by Parmesh119** [swapnilsparsh/DevEmpire#299]
DevNetwork Advisory Board is a global open-source board that helps the developer to showcase and prove their potential in front of the world and by attending their conference you can learn to expand your network and increase your knowledge.

**Comment by swapnilsparsh** [comment]
@Parmesh119 Sorry to say but In order to earn a level tag, contributors must make significant contributions to the project. This could include adding new features, fixing bugs, or improving documentation.
