### ISSUE TITLE
Improve the Footer UI

### ISSUE THREAD

**Issue by Sriparno08** [swapnilsparsh/DevEmpire#301]
I want to improve the footer UI in the website.

![Screenshot 2023-06-21 132749](https://github.com/swapnilsparsh/DevEmpire/assets/89148144/c4244a5a-b3dc-456b-86dd-4eba9d734e6c)

**Comment by swapnilsparsh** [comment]
@Sriparno08 Sure, share the designs before implementing them.

**Comment by Sriparno08** [comment]
Hey @swapnilsparsh, here is the design:

![Screenshot 2023-06-22 122248](https://github.com/swapnilsparsh/DevEmpire/assets/89148144/47673147-adbf-407f-a66f-be7b1d4e6c88)

**Comment by swapnilsparsh** [comment]
@Sriparno08 No need
