### ISSUE TITLE
Change the colour of few components of website 

### ISSUE THREAD

**Issue by I-shika** [swapnilsparsh/DevEmpire#308]
I want to change the colour  of few components for light mode as follows. As at present time the colour are not being suited .
The below picture shos the change I want in every component ,

![Screenshot (67)](https://github.com/swapnilsparsh/DevEmpire/assets/100770197/cf10c76b-7079-441a-bdea-e91b2be6058c)

For dark mode I want to change all the changed colours to white or light one and the colour of cards also.as it is not looking good right now.The below screenshot shows the current image of website
![Screenshot (68)](https://github.com/swapnilsparsh/DevEmpire/assets/100770197/a7fbfad6-9520-4a1c-bfb0-b14220b0332f)

Please assign this issue to me under GSSoC'23

**Comment by swapnilsparsh** [comment]
@I-shika Not required as of now.
