### ISSUE TITLE
Add Web Dev Tools

### ISSUE THREAD

**Issue by Sriparno08** [swapnilsparsh/DevEmpire#309]
I want to add these web dev tools to the website:

Illustration: Absurd
Icons: Dryicons
Vectors/Svg: Vecteezy
Colors: My Color Space
CSS: CSS Doodle
Stock Photos: iStock Photos

These tools are unique and not a part of the website.

I want to contribute as part of GSSoC'23.

**Comment by swapnilsparsh** [comment]
@Sriparno08 Sorry to say but In order to earn a level tag, contributors must make significant contributions to the project. This could include adding new features, fixing bugs, or improving documentation.
