### ISSUE TITLE
Adding a Social Media Icon in the Footer

### ISSUE THREAD

**Issue by Pro-18** [swapnilsparsh/DevEmpire#310]
**Is your feature request related to a problem? Please describe.**
Adding a Social Media Icon in the Footer which include github, twitter, facebook etc 
![footer](https://github.com/swapnilsparsh/DevEmpire/assets/92087279/2bc6d53b-8ffd-4969-8788-0ad99586287e)

In the digital age, social media has become an integral part of our daily lives. It serves as a platform for communication, information sharing, and networking. Many websites choose to incorporate social media icons in their footers as a means to enhance user engagement and connect with their audience.

**Describe alternatives you've considered**
While incorporating social media icons in the footer can be seen as a way to connect with users and enhance online presence, it is important to consider the potential drawbacks and implications
![issue11](https://github.com/swapnilsparsh/DevEmpire/assets/92087279/94a38d63-2691-4ed4-ab8d-22fb97aa8f03)

**Comment by swapnilsparsh** [comment]
@Pro-18 Not required as of now
