### ISSUE TITLE
Adding backend resources in webdev

### ISSUE THREAD

**Issue by Deepanshu0703** [swapnilsparsh/DevEmpire#311]
**Is your feature request related to a problem? Please describe.**
As of now there is only css and illustrator resources are there in the project but i want to add some backend resources like various platform to get free api, and other backend stuuf like api key for their dev journey.

**Comment by swapnilsparsh** [comment]
@Deepanshu0703 You have to create a whole new page for "Backend" and add all the backend stuff there.

**Comment by Deepanshu0703** [comment]
Ya I am working on it.

**Comment by swapnilsparsh** [comment]
> Ya I am working on it.

Add new route and page for "Backend" also make changes on the landing page. Good Luck 👍
Add minimum 10 tools.
