### ISSUE TITLE
Adding a Social Media Icons in the Footer

### ISSUE THREAD

**Issue by Pro-18** [swapnilsparsh/DevEmpire#312]
Many websites choose to incorporate social media icons in their footers as a means to enhance user engagement and connect with their audience
![footer](https://github.com/swapnilsparsh/DevEmpire/assets/92087279/65bb3afa-a01b-437e-9c0e-1c18381baf15)
![issue11](https://github.com/swapnilsparsh/DevEmpire/assets/92087279/417cce6a-d8b0-498d-8fda-f8a375cdeb08)

**Describe the solution you'd like**
A social media buttons include twitter, linkedin and githb .

**Comment by swapnilsparsh** [comment]
@Pro-18 Not needed
