### ISSUE TITLE
<Enhancement> UI color interface improvement 

### ISSUE THREAD

**Issue by dheeraj1129** [swapnilsparsh/DevEmpire#320]
Can we improve the color combination of the website it's like the similar colors used for the heading, and paragraph, background.
I attach some examples
![Screenshot (34)](https://github.com/swapnilsparsh/DevEmpire/assets/72201773/9f1a56b3-847f-4fd3-8b13-167b0eb60dc6)
![Screenshot (35)](https://github.com/swapnilsparsh/DevEmpire/assets/72201773/f9d07790-721b-4b9c-9547-41a7ede87d28)

e..

**Comment by swapnilsparsh** [comment]
@dheeraj1129 Not needed .Thank You 🙂
