### ISSUE TITLE
Add Hackathon Page with Hackathon Cards and Search/Filter Functionality

### ISSUE THREAD

**Issue by Nishitbaria** [swapnilsparsh/DevEmpire#322]
**Is your feature request related to a problem? Please describe.**
As part of enhancing the user interface and user experience of our project, we need to add a dedicated Hackathon page. This page will display various hackathon events in the form of cards, along with search and filter functionality to make it easier for users to find and explore hackathons based on their preferences.

**Describe the solution you'd like**
- Create a new Hackathon page to showcase hackathon events.
- Implement hackathon cards to display relevant information about each event.
- Enable search functionality to allow users to search for hackathons based on keywords.
- Implement filtering options to help users narrow down hackathon results based on specific criteria.

**Describe alternatives you've considered**

**Additional context**
- Create a new Hackathon page to showcase hackathon events.
- Implement hackathon cards to display relevant information about each event.
- Enable search functionality to allow users to search for hackathons based on keywords.
- Implement filtering options to help users narrow down hackathon results based on specific criteria.

**Comment by swapnilsparsh** [comment]
@Nishitbaria Add a minimum of 10 hackathons.

**Comment by Nishitbaria** [comment]
@swapnilsparsh ,please check my pull request
