### ISSUE TITLE
add contributors page 

### ISSUE THREAD

**Issue by shivaniyuvrajyadav** [swapnilsparsh/DevEmpire#324]
**Is your feature request related to a problem? Please describe.**
Creatied a seperate page containing the images and info about contributors of of this project.

**Additional context**

**Comment by swapnilsparsh** [comment]
@shivaniyuvrajyadav Instead of creating another page. Create a new section on the landing page there only make the changes.

**Comment by Nishitbaria** [comment]
@swapnilsparsh Assign this issue to me I will Fix it
