### ISSUE TITLE
[Feature] Add a Hovering effect on cards

### ISSUE THREAD

**Issue by Srishtikumari2002** [swapnilsparsh/DevEmpire#325]
I am willing to add a Hovering effect on each card to highlight them separately when the cursor points to them. 
For example:
![Screencast from 29-06-23 05_01_37 PM IST](https://github.com/swapnilsparsh/DevEmpire/assets/77767357/016d3c36-984b-40a9-9364-e9e916d1ba38)

**Comment by swapnilsparsh** [comment]
@Srishtikumari2002 Not needed .Thank You 🙂
