### ISSUE TITLE
Add hovering effect on the buttons of the card

### ISSUE THREAD

**Issue by Arnabhit** [swapnilsparsh/DevEmpire#326]
**Is your feature request related to a problem? Please describe.**
Whenever a button is clicked present on the card it does not look lively as the effect is very fade and slow.

**Describe the solution you'd like**
Whenever one hovers through the buttons it will give a lively glowing effect

**Describe alternatives you've considered**

**Additional context**

**Comment by swapnilsparsh** [comment]
@Arnabhit Share some designs before implementing them.
