### ISSUE TITLE
Add hyperlink under devempire on the footer which redirects to the github page

### ISSUE THREAD

**Issue by smty2018** [swapnilsparsh/DevEmpire#329]
**Is your feature request related to a problem? Please describe.**
Add hyperlink under devempire on the footer which redirects to the github page

**Describe the solution you'd like**
![image](https://github.com/swapnilsparsh/DevEmpire/assets/74114936/4f4e4e29-1442-4e60-a7d1-d92751d635ee)

**Describe alternatives you've considered**

**Additional context**

**Comment by swapnilsparsh** [comment]
@smty2018 Not needed .Thank You 🙂
