### ISSUE TITLE
Dockerize Project

### ISSUE THREAD

**Issue by shraddha761** [swapnilsparsh/DevEmpire#331]
**Is your feature request related to a problem? Please describe.**
Create a docker file for project which help to you to package your application and its dependencies into a container, making it highly portable. The Docker image can be run on any system that supports Docker, ensuring consistent behavior across different environments. It allow you define the exact steps needed to build your application environment. By versioning your Dockerfile, you can reproduce the exact same environment at any point in the future. This helps avoid "it works on my machine" issues and facilitates collaboration among team members.

Assign this issue to me under GSSOC'23

**Comment by swapnilsparsh** [comment]
@shraddha761 Make the project docker friendly but also make sure if someone does not have docker then he/she can run the project without the need of docker.
