### ISSUE TITLE
add appwrite in the backend development 

### ISSUE THREAD

**Issue by shivaniyuvrajyadav** [swapnilsparsh/DevEmpire#339]
**Describe the solution you'd like**
Appwrite is a backend platform for developing Web, Mobile, and Flutter applications. we can add this in the backend resources .

**Comment by swapnilsparsh** [comment]
@shivaniyuvrajyadav Sorry to say but In order to earn a level tag, contributors must make significant contributions to the project. This could include adding new features, fixing bugs, or improving documentation
