### ISSUE TITLE
Want to add Games in the Games Section

### ISSUE THREAD

**Issue by killerraj369** [swapnilsparsh/DevEmpire#342]
**Is your feature request related to a problem? Please describe.**
There are very few and not so impressive games

**Describe the solution you'd like**
I would like to add good games in the Project.

**Describe alternatives you've considered**

**Additional context**

**Comment by killerraj369** [comment]
Kindly Assign me this issue

**Comment by swapnilsparsh** [comment]
If you have complete the work, then please let me know that you are facing some issue. I closed this issue because you were inactive.

**Comment by killerraj369** [comment]
@swapnilsparsh Thanks a lot for reopening the issue. 
I have completed my work and opened up PR #362 .You can take a review and proceed to merge.
