### ISSUE TITLE
Newsletter button is non functional, Want to add newsletter in the footer

### ISSUE THREAD

**Issue by killerraj369** [swapnilsparsh/DevEmpire#343]
**Is your feature request related to a problem? Please describe.**
Newsletter button is present, but it is not working. Want to integrate newsletter option in the footer itself.

**Describe the solution you'd like**
will implement newsletter functionality.

**Additional context**

**Comment by swapnilsparsh** [comment]
@killerraj369 we will be adding it soon. Not required as of now.
