### ISSUE TITLE
Bug in Navbar 

### ISSUE THREAD

**Issue by swapnilsparsh** [swapnilsparsh/DevEmpire#345]
When you open the website in phone and then you click on the DevEmpire which is there in header and after that if you click any link page like "ambassador" or "games" then the Navbar get open up which should not open. Same goes when you click on any page number then also the Navbar gets open up.

![Screenshot_2023-07-08-22-44-48-017_com.android.chrome-edit.jpg](https://github.com/swapnilsparsh/DevEmpire/assets/69387608/e88d0fe6-d3b1-47ca-a633-7fbfd9e09b62)

**Comment by Abhinavcode13** [comment]
Assign me this @swap

**Comment by Nishitbaria** [comment]
@swapnilsparsh Assign me i will look into it
