### ISSUE TITLE
🔍 Bug: Hackathon NavItem not visible in Android 📱 – Ensuring Consistency and User Experience

### ISSUE THREAD

**Issue by Nishitbaria** [swapnilsparsh/DevEmpire#352]
**Describe the bug**

🐛 There seems to be a bug 🐞 where the Hackathon NavItem is visible on a normal screen (Laptop) 👩‍💻, but it is not visible in the Android view 📱. This issue needs to be addressed to ensure consistency across different devices 📺 and provide a seamless user experience. 🌟

**To Reproduce:**
1. Open the application on a laptop or desktop computer. 
2. Navigate to the navigation bar.
3. Verify that the Hackathon NavItem is visible.

**Expected behavior:**
The Hackathon NavItem should be visible on all devices, including Android view.

**Actual Behavior:**
The Hackathon NavItem is not visible in the Android view, causing an inconsistency in the user interface.

**Screenshots**

https://github.com/swapnilsparsh/DevEmpire/assets/85815172/4a4a437f-2905-45e2-8da5-25b00e123e39

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Brave, Chrome, Edge

**Smartphone (please complete the following information):**
 - Device: Redmi Note 8
 - OS: Android 
 - Browser: Chrome, Edge, Brave

**Additional context**

**Comment by Nishitbaria** [comment]
@swapnilsparsh Please Assign this issue

**Comment by swapnilsparsh** [comment]
@Nishitbaria Any update on this ?
