### ISSUE TITLE
[FEAT]: META ELEMENTS TO IMPROVE SEO 🚀

### ISSUE THREAD

**Issue by 0xabdulkhalid** [swapnilsparsh/DevEmpire#354]
**Is your feature request related to a problem? Please describe.**
- This feature is related to the Search Engine Optimization Problem

**Describe the solution you'd like**
- The `<meta>` elements in HTML are used to provide metadata or additional information about an HTML document. 
- They help with specifying the character encoding, defining the viewport for responsive design, setting the page title, and providing page descriptions. 
- They assist search engines, browsers, and other web applications in understanding and processing the webpage's content effectively.
- I want to add important Meta elements because in HTML they play a crucial role in providing information about the webpage to browsers and search engines and for the above mentioned reasons.

**Describe alternatives you've considered**
- There's no alternatives to improve SEO rather than adding `meta` elements.

**Comment by 0xabdulkhalid** [comment]
Hey there @swapnilsparsh 👋🏻

Please make sure to assign this issue to me as soon possible so that i can make the work done!

Thank you.

**Comment by swapnilsparsh** [comment]
@0xabdulkhalid Meta tags are already there in code.
