### ISSUE TITLE
[BUG]: Scroll Bar Behavior is Stop and Go Action in All Pages

### ISSUE THREAD

**Issue by NarendraKoya999** [swapnilsparsh/DevEmpire#357]
**Describe the bug**
### GSSOC'23
- **Scroll Bar Behavior is Stop and Go Action in All Pages**

**To Reproduce**
1. Go to 'https://devempire.netlify.app/'
2. Click on **'Any Page Related Options'**
3. Scroll down to **'Bottom of the any Page'** 
4. See the error on **Respective Web Page when clicking on Scroll Bar Icon**

**Expected behavior**
- **CSS related Modifications need to resolve Scroll Bar Issues** 

**Screenshots**

https://github.com/swapnilsparsh/DevEmpire/assets/84512164/5545bc54-50e8-46de-8e8f-0f29b2f4bf39

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by swapnilsparsh** [comment]
@NarendraKoya999 I checked and its working fine,
