### ISSUE TITLE
[OTHER] :  Improving Website loading and working

### ISSUE THREAD

**Issue by parasss19** [swapnilsparsh/DevEmpire#358]
- The images on the website are taking time to load as they are in png/jpeg format.

- I will convert it into webp format

### Smaller File Size : 
- WebP images typically have a smaller file size compared to PNG images while maintaining similar image quality. This results in faster webpage loading times, reduced bandwidth usage, and improved overall user experience.
### Wide Browser Support:
-  WebP is supported by major web browsers, including Google Chrome, Opera, and Microsoft Edge. Additionally, popular image editing software like Adobe Photoshop and GIMP provide WebP support, making it easy to work with these files.
### Animation Support: 
- WebP format also supports animation, similar to the GIF format. It can store multiple frames within a single image file, allowing you to create lightweight animations for websites.

**Comment by swapnilsparsh** [comment]
@parasss19 Convert all the images which are there on website without loosing the quality of the image
