### ISSUE TITLE
No description for any card

### ISSUE THREAD

**Issue by tnmyk** [swapnilsparsh/DevEmpire#36]
Some PR has removed the descriptions from the cards in everypage.
Current state of the cards : 
![image](https://user-images.githubusercontent.com/73903781/135760406-b1aeaf10-8215-4740-8d05-94ea7131414c.png)

How it should have been :
![image](https://user-images.githubusercontent.com/73903781/135760436-10682d95-d721-4490-bf8f-fbeefa8baa24.png)

I would like to fix this...

**Comment by tnmyk** [comment]
Cause : PR #32

**Comment by sofisdev** [comment]
I can take care of this! 😀

**Comment by tnmyk** [comment]
@sofisdev u can work on this if u want to..

**Comment by swapnilsparsh** [comment]
> I can take care of this! 😀

Should  I assign this issue to you? 😀

**Comment by swapnilsparsh** [comment]
> @sofisdev u can work on this if u want to..

@sofisdev Should I assign this issue to you? 😀

**Comment by B1TSH3LL** [comment]
I can work on this issue can you assign it
