### ISSUE TITLE
Footer is not responsive in mobile device

### ISSUE THREAD

**Issue by crocmons** [swapnilsparsh/DevEmpire#360]
The footer is not responsive on mobile devices...I want to make a responsive footer for all devices,  assign this issue to me as a GSSOC23 contributor
![Screenshot (11)](https://github.com/swapnilsparsh/DevEmpire/assets/106610322/67f0018a-8d09-4809-9503-b724bfd07e6c)

**Comment by swapnilsparsh** [comment]
@crocmons It is working fine, can you provide the resolution on which you are facing this issue.

**Comment by crocmons** [comment]
Hey, it's still there at 320 resolution...It is not responsive on smaller devices @swapnilsparsh 
![Screenshot (496)](https://github.com/swapnilsparsh/DevEmpire/assets/106610322/23ad24ee-f7d9-4fba-a7e8-4bbaabff2e8f)
