### ISSUE TITLE
Repetitive items in Backend Page and Addition of more items

### ISSUE THREAD

**Issue by killerraj369** [swapnilsparsh/DevEmpire#363]
**Describe the bug**
Hello Project Admin,
I have seen repetitive items in the Backend Page. I would like to resolve this and add more backend items from my side.

**To Reproduce**
1. Go to 'Backend Page in the navbar'

**Expected behavior**
The website would become more useul if more resources are added in the website. hence I would like to add more backend technologies. So that a user have access to a plethora of items.

**Screenshots**
![2023-07-14](https://github.com/swapnilsparsh/DevEmpire/assets/87773889/7d032496-857f-440b-a8c2-9e5600cf2662)

**Comment by Deepanshu0703** [comment]
Hey @swapnilsparsh actually it's not repitative firebase can be used as both database and hosting purpose , So one firebase is coming into the category of database and another in hosting category

**Comment by swapnilsparsh** [comment]
@Deepanshu0703 yes but you have to show only 1 firebase with multiple tags so that it can be shown in both hoting and database.

**Comment by Deepanshu0703** [comment]
yes fror that instead of a single category , we have to use array of category.

**Comment by swapnilsparsh** [comment]
@Deepanshu0703 Yes

**Comment by Deepanshu0703** [comment]
Hey @swapnilsparsh  can you assign this task to me. Also it is requested that it is not a level1 work.
