### ISSUE TITLE
Auto assign feature 

### ISSUE THREAD

**Issue by andoriyaprashant** [swapnilsparsh/DevEmpire#365]
**Is your feature request related to a problem? Please describe.**
By implementing the Auto Issue Assignment feature using GitHub Actions, the issue assignment process becomes automated and efficient. Issues matching specific comment-based criteria will be automatically assigned to the user who made the relevant comment, improving collaboration and task management within the repository.

**Describe the solution you'd like**
- Add Auto assign feature

**Additional context**
- Path (.github\workflow)

**ScreenShort -**
![Screenshot 2023-07-13 234416](https://github.com/swapnilsparsh/DevEmpire/assets/121665385/bcdd0849-f139-41d4-a635-dec0b66c298c)

**Comment by andoriyaprashant** [comment]
Hey @swapnilsparsh Please review my pull request #366 
Thank you

**Comment by swapnilsparsh** [comment]
@andoriyaprashant Great idea but I don't want to auto assign the issues without reviewing the issue. As it will mess and chaos in PR.
