### ISSUE TITLE
Enhancement on ui of Cards 

### ISSUE THREAD

**Issue by I-shika** [swapnilsparsh/DevEmpire#367]
**Is your feature request related to a problem? Please describe.**
I want to modify the designs of cards for this website 
![Screenshot (131)](https://github.com/swapnilsparsh/DevEmpire/assets/100770197/5ed8da18-2227-4c41-85e5-11290789b4c6)

**Describe the solution you'd like**
As of now the cards are really simple so I want to do some changes in present ui and add some hover effect on it.

**Describe alternatives you've considered**

**Additional context**

Please assign this issue to me under GSSoC'23.

**Comment by I-shika** [comment]
I want to replace the cards design similar to the below one in which first image is without hover effect and another one is on hover.
![Screenshot (132)](https://github.com/swapnilsparsh/DevEmpire/assets/100770197/0a87883e-de69-4d62-a0c6-795e02285063)
![Screenshot (133)](https://github.com/swapnilsparsh/DevEmpire/assets/100770197/c11ad0d2-d59d-4f71-91cc-e0491f87afd7)

**Comment by swapnilsparsh** [comment]
@I-shika Look for some other designs

**Comment by Bashamega** [comment]
@swapnilsparsh 
Hello:)
I can make that when you hover on it goes bigger, and also have a glow effect like this, but with more blue.
![image](https://github.com/swapnilsparsh/DevEmpire/assets/110662505/25a31e50-923a-4e61-8230-34ca36ce710d)

**Comment by swapnilsparsh** [comment]
@Bashamega Not looking very impressive.
