### ISSUE TITLE
Enhancing links in Footers

### ISSUE THREAD

**Issue by Avinash905** [swapnilsparsh/DevEmpire#368]
**Is your feature request related to a problem? Please describe.**
Currently the links in footer are just contain link with text in it.

**Describe the solution you'd like**
- I would like to add icons beside the all footer links which resemble them.
- This feature aims to improve the accessibility of links within the footer by implementing a solution for screen reader users.
- Would change the color of the links in footer while hovering them.

**Comment by swapnilsparsh** [comment]
@Avinash905 Also change the footer color when switching from dark mode to light mode and vice-versa
