### ISSUE TITLE
Filter Option in Web Dev Page not working

### ISSUE THREAD

**Issue by jatiinyadav** [swapnilsparsh/DevEmpire#37]
While clicking on the  ` Illustration`, `Icons`, and all the filters the resources are not showing according to the filter.

![InkedScreenshot (32)_LI](https://user-images.githubusercontent.com/73248007/135760716-8a50a868-a7bb-42cd-b735-9c3517439597.jpg)

**Comment by tnmyk** [comment]
Basically PR #32 Is giving issues. Issue #36 is also due to same PR.

**Comment by jatiinyadav** [comment]
Okay, we got it 👍🏻.
This bug has to be resolved asap, so if possible can you please fix it?

**Comment by tnmyk** [comment]
Yea u can assign me...
