### ISSUE TITLE
Navbar redesign

### ISSUE THREAD

**Issue by BhartiNagpure** [swapnilsparsh/DevEmpire#372]
As a developer point of view I would like to redesign navbar.
 I make sure all menu will be shown.
 and also want to add navbar hide and show functionality at certain height which looks nice than the sticky navbar.

**Comment by swapnilsparsh** [comment]
@BhartiNagpure 
I have share the design. make it like this

- In place of 1 there will be DevEmpire writtern
- In place of 2 there will be GitHub logo which will redirect to repo 
- In place of 3 there will dark mode button 
- Search will be same as it is right now

### Big Screen
![image](https://github.com/swapnilsparsh/DevEmpire/assets/69387608/5b22faa9-cfc6-4b1c-a495-19f8f191cf06)

### Mobile Screen 
![image](https://github.com/swapnilsparsh/DevEmpire/assets/69387608/f890718c-b956-4978-9d79-88d532810fc3)
