### ISSUE TITLE
Hackathon Description in Landing Page 

### ISSUE THREAD

**Issue by Deepanshu0703** [swapnilsparsh/DevEmpire#376]
**Is your feature request related to a problem? Please describe.**
Yes, As like other features like backend , web dev and other you have description of them on the landing page but there is not description of Hackathon on Landing Page.

**Describe the solution you'd like**
I want to add the png image related to hackathon and a short description as given in other features.

![image](https://github.com/swapnilsparsh/DevEmpire/assets/114489502/ac92a7c8-ecd3-4205-87d9-cba92b8d8b68)

**Comment by swapnilsparsh** [comment]
@Deepanshu0703 Choose similar illustration which should look well with others illustrations.
