### ISSUE TITLE
Want to add Next Auth Google Provider For Sign up

### ISSUE THREAD

**Issue by crocmons** [swapnilsparsh/DevEmpire#377]
Want to add Next Auth Signup Google provider ...Could you assign this issue to me as a GSSOC23 contributor?

![Screenshot (500)](https://github.com/swapnilsparsh/DevEmpire/assets/106610322/2c2960dc-ed4a-43d4-8ace-993d0c535d2c)

**Comment by swapnilsparsh** [comment]
@crocmons There is not authentication on our website. So not needed.
