### ISSUE TITLE
Want to improve the readme file By adding Gssoc template .

### ISSUE THREAD

**Issue by HimanshuNarware** [swapnilsparsh/DevEmpire#381]
**Is your feature request related to a problem? Please describe.**
Readme file is missing Gssoc template

**Describe the solution you'd like**
I want to improve the readme file by adding the title of
This Open-Source project is a part of GSSOC

##Screenshot
![74](https://github.com/swapnilsparsh/DevEmpire/assets/83147410/d05c4455-04af-4740-bb8d-9e95f7157461)

**Comment by swapnilsparsh** [comment]
@HimanshuNarware Not Required.
