### ISSUE TITLE
Hover effect on cards

### ISSUE THREAD

**Issue by parasss19** [swapnilsparsh/DevEmpire#383]
## Currently
- The DevEmpire website contains so many cards (hackathons, programs, web dev, games)
- Cards are the main element in your  website and right now cards doesn't look great as there are no effects on hover

## Solution
- I will add hover effect on every cards using tilt.js library (its a glass effect and looks great in your website )
- Or you can also suggest the effect you want  I will do accordingly

**Comment by swapnilsparsh** [comment]
@parasss19 Can you share some designs before implementing them?

**Comment by parasss19** [comment]
> @parasss19 When I hover on the card then I want the Image only to move back a little like zoom out effect and when I remove the cursor from that card then the image should come back to its original size with some zoom in effect.

Oki I will work on this assign me this issue
