### ISSUE TITLE
Contributors page

### ISSUE THREAD

**Issue by AlfiyaSiddique** [swapnilsparsh/DevEmpire#386]
### Is your feature request related to a problem? Please describe.

As this is an open-source project having a section dedicated to contributors is a common practice. I would like to add a page that contains the contributor's information in the card form.

### Describe the solution you'd like

We can use the GitHub API to get the list of contributors for this project and display them on our website. This will encourage developers to contribute to this project.

**Request** 

I am a gssoc23 contributor please assign me this issue under gssoc23 label.

**Comment by swapnilsparsh** [comment]
@AlfiyaSiddique Already in process, I will make the changes.
