### ISSUE TITLE
Add CodeQl workflow

### ISSUE THREAD

**Issue by andoriyaprashant** [swapnilsparsh/DevEmpire#391]
**Is your feature request related to a problem? Please describe.**

By integrating the CodeQL static analysis tool into our development process, we aim to enhance the security and quality of our codebase significantly. CodeQL's language-agnostic nature, interprocedural analysis, and GitHub Actions integration make it an invaluable addition to our development toolkit. This proposal seeks to fortify our software projects against potential vulnerabilities and maintain the highest standard of code quality throughout our development lifecycle.

CodeQL is language-agnostic, meaning it supports a wide range of programming languages, including Java, JavaScript, C/C++, Python, C#, Go, Ruby, Swift, HTML, and CSS, among others.

**Describe the solution you'd like**
Add CodeQl workflow

**Additional context**
GSSOC 2023

**Comment by swapnilsparsh** [comment]
@andoriyaprashant Not Required
