### ISSUE TITLE
Navbar and footer for darkmode

### ISSUE THREAD

**Issue by anamika7153** [swapnilsparsh/DevEmpire#393]
### I'm in GSSoC'23

**Describe the bug**
- Navbar and footer doesn't seem to be compatible for the dark mode.

**To Reproduce**
1. Go to 'website'
2. Click on 'darkmode toggle button' and switch to darkmode
3. See the navbar and footer

**Expected behavior**
- Navbar and footer color should be compatible with the dark theme.

**Screenshots**
<img width="660" alt="image" src="https://github.com/swapnilsparsh/DevEmpire/assets/66116440/40e444b0-bbd9-49d8-ac23-2cf486c55f78">

**Comment by anamika7153** [comment]
> Hey @anamika7153, This issue is closed.

Thanks for reviewing and merging. I wanted to ask if you will be active for a couple of days or no as the program is approaching its end and many PAs are inactive. I wanted to make another PR.

**Comment by swapnilsparsh** [comment]
@anamika7153 Yes I will be active 😀
