### ISSUE TITLE
💭 Missing Description and 🖼️ Vector Image for Hackathon Section on Home Page

### ISSUE THREAD

**Issue by Nishitbaria** [swapnilsparsh/DevEmpire#395]
**Describe the bug**
🚫 DevEmpire Home Page is currently lacking both a descriptive text and an accompanying vector image for Hackathon Section . While other sections like Home, Ambassador, and Programs have their respective descriptions and vector image, the Hackathon section is incomplete.

_**`I will take the initiative to add the necessary description and find an appropriate vector image that reflects the theme of hackathons. I'll ensure that the formatting and CSS are in line with the overall design of the website.`**_

**To Reproduce**
1. 🌐 Go to the [DevEmpire Website](https://devempire.netlify.app/).
2. 📜 Scroll down to the sections on the homepage.
3. ❌ Observe that the Hackathon section is absent.
 
**Expected behavior**
We expect the Hackathon section to have a clear and concise description, as well as a suitable vector image that represents the essence of hackathons, just like other sections on the website.

**Screenshots**

https://github.com/swapnilsparsh/DevEmpire/assets/85815172/5ba018ab-7ce5-4e9e-bbd9-08623f9f25aa

**Comment by Nishitbaria** [comment]
@swapnilsparsh Please review my issue

**Comment by Nishitbaria** [comment]
@swapnilsparsh what is the source of you vector images and icons for homepages

**Comment by swapnilsparsh** [comment]
@Nishitbaria They are are not from one single source. I guess you have to find it hard by yourself.

**Comment by Nishitbaria** [comment]
> @Nishitbaria They are are not from one single source. I guess you have to find it hard by yourself.

Ok THanks for let me know i will find best match
