### ISSUE TITLE
[Feat]:  Want to add CodeQl & Greetings file

### ISSUE THREAD

**Issue by crocmons** [swapnilsparsh/DevEmpire#397]
### What feature?

![Screenshot (29)](https://github.com/swapnilsparsh/DevEmpire/assets/106610322/9e357584-2671-4d1e-aa23-e0ec6a42b731)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by swapnilsparsh** [comment]
@crocmons Not needed
