### ISSUE TITLE
Add a Call to Action Button on Landing Page

### ISSUE THREAD

**Issue by swapnilsparsh** [swapnilsparsh/DevEmpire#4]
When clicking on Call to Action it should scroll down to the Ambassador section.

**Comment by tnmyk** [comment]
I would love to work on this too!

**Comment by tnmyk** [comment]
Also can add more details? Exactly where do you want the button to be?

**Comment by swapnilsparsh** [comment]
> Also can add more details? Exactly where do you want the button to be?

Just beside the Discord Button.
