### ISSUE TITLE
[Bug]: the pagination issue

### ISSUE THREAD

**Issue by k-deepak04** [swapnilsparsh/DevEmpire#403]
### Description

the pagination should come in 1 line also it's displaying all the pages for now it's 7 but if data grows it will be difficult to display all
so i will modify the pagination to display only few pages rest ..... 
like 1 2 3 ....... 24 25.

### Expected Behavior

1 2 3 ....... 24 25.
look like this and come in 1 line

### Show us the trouble with screenshots

![image](https://github.com/swapnilsparsh/DevEmpire/assets/96341431/c2b92676-a537-4fd6-a47a-1572b81da2ee)

### Enter the version of your web browser

n/a

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by k-deepak04** [comment]
okay i will file a pr soon.

**Comment by vatan999** [comment]
@swapnilsparsh Iwould like to work on this issue. please assign it to me.

**Comment by Abinash018** [comment]
I would like to work on this issue. please assign  me :)

**Comment by Nil2000** [comment]
Hi @swapnilsparsh Is this the one you are looking for?

![image](https://github.com/swapnilsparsh/DevEmpire/assets/54113952/4c07ccb8-9f04-408f-8fca-fc4664cefd49)

**Comment by swapnilsparsh** [comment]
> Hi @swapnilsparsh Is this the one you are looking for?
> 
> ![image](https://github.com/swapnilsparsh/DevEmpire/assets/54113952/4c07ccb8-9f04-408f-8fca-fc4664cefd49)
> 

Yes

**Comment by Nil2000** [comment]
You can assign me this task if it's okay from your side.

**Comment by swapnilsparsh** [comment]
@Nil2000 We are removing this pagination thing in v2.
