### ISSUE TITLE
[Bug]: Missing Tooltip-title Attribute  for All Social Icons and Other Important Areas

### ISSUE THREAD

**Issue by NarendraKoya999** [swapnilsparsh/DevEmpire#405]
### Description

- **Missing Tooltip for All Social Icons and Other Important Areas.**
 ### Purpose of Raising this Issue
- The text of the title attribute is displayed as a tooltip in most browsers — it appears in a small bubble when the cursor hovers over the link. Originally, this was intended to be used to indicate the title of the linked document. This is still a good practice, but you may use it for any text which you think will be helpful to the user.

### Expected Behavior

- After adding title attribute to required social Icons and Other wanted Areas. Every Important Icon area indicated Some Helpful Text.

### Show us the trouble with screenshots

![devempire-1](https://github.com/swapnilsparsh/DevEmpire/assets/84512164/7020a9d8-5e57-464f-a40a-06e25da407d5)

### Which browsers are affected?

Chrome

### Which OS are affected?

Windows

### Enter the version of your web browser

**Google Chrome- Version 115.0.5790.110 (Official Build)**

### Device?

Desktop

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by swapnilsparsh** [comment]
@NarendraKoya999 Not required.
