### ISSUE TITLE
[Bug]: improve footer and its responsiveness

### ISSUE THREAD

**Issue by ratishjain12** [swapnilsparsh/DevEmpire#407]
### Description

the footer items are getting overlapped on resize and is not looking

### Expected Behavior

I want to fix the layout of the footer and improve its responsiveness

### Show us the trouble with screenshots

![Annotation 2023-07-31 153353](https://github.com/swapnilsparsh/DevEmpire/assets/43003421/c9a873df-59db-4655-af28-fd4cc6218a99)

### Enter the version of your web browser

-

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by swapnilsparsh** [comment]
@ratishjain12 Go ahead 👍
