### ISSUE TITLE
Adding Dependency Update Workflow and Refactoring Issue Template ✨

### ISSUE THREAD

**Issue by Nishitbaria** [swapnilsparsh/DevEmpire#410]
**Issue Description:**
As the project continues to grow, it becomes essential to enhance our automation and project management processes. This issue proposes the implementation of two crucial workflows: Dependency Update Workflow and Refactoring Issue Template, along with adding CodeQL and Prettier workflows to ensure code quality and formatting consistency.

**1. Dependency Update Workflow:**
We need to set up a dedicated workflow to automatically update project dependencies regularly. This workflow will run on a scheduled basis, or upon manual triggering, to check for the latest versions of dependencies and update them in a controlled manner. By doing so, we ensure our project stays secure, up-to-date, and free from potential vulnerabilities.

The workflow should include the following steps:
- Fetch the latest dependency versions.
- Run tests and checks against the updated dependencies to identify potential issues.
- Create a pull request with the dependency updates.
- Notify the maintainers for review and approval.

**2. Refactoring Issue Template:**
Refactoring is a crucial aspect zof maintaining a clean and sustainable codebase. To streamline the process and make it more efficient, we should introduce a standard Refactoring Issue Template. This template will help developers document and communicate the refactoring tasks clearly, making it easier for everyone to understand the context and objectives of the refactoring process.

The Refactoring Issue Template should include sections such as:
- Description of the current code status.
- Clear objectives and reasons for the refactoring.
- Proposed changes and improvements.
- List of affected files or components.
- Impact on the project after refactoring.

**3. CodeQL Workflow:**
CodeQL is an excellent tool for identifying and fixing security vulnerabilities in our codebase. By adding a CodeQL workflow, we can automatically run security scans, detect potential vulnerabilities, and provide detailed reports on any issues found. This will significantly enhance our code security and reliability.

**4. Prettier Workflow:**
Maintaining consistent code formatting is crucial for code readability and collaboration. With a Prettier workflow, we can automatically check if the code adheres to the defined formatting standards and automatically fix any deviations. This ensures a unified code style across the entire project.

**Benefits:**
- Improved project security with regular dependency updates.
- Efficient refactoring process with a clear and standardized template.
- Enhanced code security through CodeQL scans.
- Consistent code formatting for better code readability and collaboration.

**Comment by Nishitbaria** [comment]
Hey @swapnilsparsh please review and assign me this issue these changes make your project more effective

**Comment by swapnilsparsh** [comment]
@Nishitbaria All of the things mentioned are not required as of now. Thank you 😀
