### ISSUE TITLE
[Bug]: Redundant and Missing Backend Tools on DevEmpire

### ISSUE THREAD

**Issue by Nishitbaria** [swapnilsparsh/DevEmpire#417]
### Description

Currently, the Backend Tools category page on the DevEmpire website contains redundant tools and lacks some relevant tools. This issue affects the accuracy and usefulness of the platform by presenting users with outdated or irrelevant information.

### Expected Behavior

The Backend Tools category page should provide users with a curated list of up-to-date and relevant tools for backend development. Redundant tools should be removed, and missing tools should be added to ensure that users can access accurate and valuable information.

### Expected Behavior

The Backend Tools category page should provide users with a curated list of up-to-date and relevant tools for backend development. Redundant tools should be removed, and missing tools should be added to ensure that users can access accurate and valuable information.

### Suggested Solution

1. **Remove Redundant Tools:** Review the list of tools on the Backend Tools category page and identify redundant ones. Remove tools that offer similar functionalities and are no longer necessary.

2. **Add Relevant Tools:** Identify missing backend tools that are widely used and relevant to the developer community. Add these tools to the category page to enhance its value.

### Show us the trouble with screenshots

![image](https://github.com/swapnilsparsh/DevEmpire/assets/85815172/8c93433f-9be7-4fdc-9b86-6cb561dc7b8e)

### Which browsers are affected?

Microsoft Edge

### Which OS are affected?

Windows

### Enter the version of your web browser

115.77.27.1

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by Nishitbaria** [comment]
@swapnilsparsh ,please assign me this issue ,i will make pull request asap

**Comment by Nishitbaria** [comment]
@swapnilsparsh ,any other issues i can work on ? ( i can integrate newsletter connected with hashnode)

**Comment by swapnilsparsh** [comment]
> @swapnilsparsh ,any other issues i can work on ? ( i can integrate newsletter connected with hashnode)

I am already working on that part you can create a new issue regarding preloader as it is not showing on the website.
