### ISSUE TITLE
[Bug]: Preloader Not Displaying on DevEmpire Website

### ISSUE THREAD

**Issue by Nishitbaria** [swapnilsparsh/DevEmpire#418]
### Description

Currently, the preloader on the DevEmpire website is not displaying as expected. The absence of the preloader impacts the user experience, as it does not provide visual feedback to users while the website content is loading.

### Steps to Reproduce

1. Navigate to the [DevEmpire Website](https://www.devempire.dev).
2. Observe that the preloader, which should appear during the loading process, is not visible.
3. Notice that there is no visual indicator to inform users about ongoing content loading.

### Expected Behavior

The preloader should be displayed on the website while the content is loading. This provides users with a clear visual cue that the website is processing their request and enhances their overall experience by reducing confusion and uncertainty.

### Suggested Solution

1. **Inspect Preloader Code:** Review the code responsible for displaying the preloader on the website to identify any errors or issues that might be causing it not to appear.

2. **Check CSS and configuration:** Ensure that the necessary CSS styles and JavaScript functions related to the preloader are correctly implemented.

3. **Test in Different Browsers:** Verify if the issue persists across different web browsers. Sometimes, certain CSS or JavaScript features may behave differently in various browsers.

### Show us the trouble with screenshots

![image](https://github.com/swapnilsparsh/DevEmpire/assets/85815172/44c53827-90d8-4795-8711-9b777ef0e506)

### Which browsers are affected?

Microsoft Edge

### Which OS are affected?

Windows

### Enter the version of your web browser

112.23.2.1.1

### Device?

Desktop

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by Nishitbaria** [comment]
@swapnilsparsh ,please assign me this issue ,i will fix this asap

**Comment by swapnilsparsh** [comment]
@Nishitbaria There is already a pre loader there you have to find the bug and fix it. Additionally show the percentage also how much page is loaded. If you have some new designs for preloader share them also.

**Comment by Nishitbaria** [comment]
>sure
