### ISSUE TITLE
[Feat]: Implement sound effects during theme toggle ✨ 

### ISSUE THREAD

**Issue by 0xabdulkhalid** [swapnilsparsh/DevEmpire#419]
### What feature?

- The feature is about using audio clips to produce sound effects during Theme Toggle.
- We want to add two types of clips each clip will have a different sound effect during toggle.
- This will create a fresh user experience for the user who uses DevEmpire.

### Show us the magic with screenshots

- I can't show screenshot for that, But i can provide you a sample [project](https://0xabdulkhalid.github.io/todo-app/) which uses this feature.

- You can test this by toggling the theme button.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by 0xabdulkhalid** [comment]
Hey there @swapnilsparsh 👋🏻 

Please make sure to assign this issue to me to make the work done, Thank You!

**Comment by swapnilsparsh** [comment]
@0xabdulkhalid Not required. Thank You
