### ISSUE TITLE
Want to add our Contributor page in the website[Feat]: 

### ISSUE THREAD

**Issue by HimanshuNarware** [swapnilsparsh/DevEmpire#421]
### What feature?

Details
Is your feature request related to a problem? Please describe.
Our Contributors page in the website
Describe the solution you'd like
We can add a Contributors page in the website. which is shows the name and the profile image of the contributor.and the number of commits is done by the contributor

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by swapnilsparsh** [comment]
@HimanshuNarware Already in progress. No required.
