### ISSUE TITLE
Adding some Open Source Programs.

### ISSUE THREAD

**Issue by helios1101** [swapnilsparsh/DevEmpire#48]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
I wanted to add some Open Source programs to the list of Open Source Programs.

**Describe alternatives you've considered**

**Additional context**

**Comment by jatiinyadav** [comment]
Can you please elaborate, which open-source programs you are going to add?

**Comment by helios1101** [comment]
The programs I'll be adding are Script Winter Of Code (SWOC) and Lets Grow More Summer Of Code (LGMSOC) .

**Comment by swapnilsparsh** [comment]
Issue resolved by @helios1101 #50
