### ISSUE TITLE
New Web Dev tools

### ISSUE THREAD

**Issue by maria5395** [swapnilsparsh/DevEmpire#55]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
I would like to add some helpful Web Development tools in which you can find some top quality images which can be used anywhere.
They are - Unsplash and Pexels.

**Describe alternatives you've considered**

**Additional context**

**Comment by jatiinyadav** [comment]
This issue #55 has been resolved by @maria5395
