### ISSUE TITLE
Description of Ambassador Programs

### ISSUE THREAD

**Issue by jatiinyadav** [swapnilsparsh/DevEmpire#57]
1. Write a **clear and concise** description of all Ambassador Programs.
2. The Ambassador Program having a heading in 2 lines their description should also be in 2 lines.
3. For reference:

![Screenshot 2021-10-08 010830](https://user-images.githubusercontent.com/73248007/136451288-eb18755e-d100-44ed-ba91-2d59b3402166.png)
-

**Comment by itsomkathe** [comment]
Hey, can you assign it to me?
