### ISSUE TITLE
Add a Preloader in the website

### ISSUE THREAD

**Issue by jatiinyadav** [swapnilsparsh/DevEmpire#58]
1. Make sure to follow the color codes.
2. You can find the color codes of the website here: [CONTRIBUTING.md](https://github.com/swapnilsparsh/DevEmpire/blob/master/CONTRIBUTING.md)

**Comment by mstofirova** [comment]
Hello, can I work on this?

**Comment by swapnilsparsh** [comment]
@mstofirova Any updates?

**Comment by mstofirova** [comment]
Sorry, i don't have time. You can assign samone else.

**Comment by akk312000** [comment]
I would like to work on this issue, can you please assign it to me @jatiinyadav .

**Comment by JanaTod** [comment]
Hi, can I work on this issue?

**Comment by swapnilsparsh** [comment]
> Hi, can I work on this issue?

Good Luck 👍🏼

**Comment by JanaTod** [comment]
@swapnilsparsh Preloader currently looks like this. What do you think? Does it look good or should I make some changes?

https://user-images.githubusercontent.com/91850076/137634699-98fdb7e2-c5df-4880-ae40-3861b2fedb65.mp4
