### ISSUE TITLE
Clicking on Heading should redirect to top of page in Landing Page.

### ISSUE THREAD

**Issue by swapnilsparsh** [swapnilsparsh/DevEmpire#6]
![Annotation 2021-09-30 232213](https://user-images.githubusercontent.com/69387608/135506072-af6428cd-9d15-409a-ac86-0941f7a60a6b.png)

**Comment by yasinbordbar** [comment]
Please assign me to do this.

**Comment by yasinbordbar** [comment]
Done!

**Comment by swapnilsparsh** [comment]
> Done!

@yasinbordbar Any updates? 🙂

**Comment by Johnisaig** [comment]
Hi @swapnilsparsh, is still open?

**Comment by swapnilsparsh** [comment]
> Hi @swapnilsparsh, is still open?

Yes

**Comment by Johnisaig** [comment]
@swapnilsparsh please review PR #25 thanks.

**Comment by swapnilsparsh** [comment]
Issue resolved by @Johnisaig #25
