### ISSUE TITLE
Add a contributors section in the README.md file 

### ISSUE THREAD

**Issue by swapnilsparsh** [swapnilsparsh/DevEmpire#62]
Just below the Project Maintainer heading add the Contributors Section.

**Comment by DarkSoul26** [comment]
@swapnilsparsh  I have tried a lot but the **markdown autodocs** is giving so many errors and the resources to resolve the same are almost none.

**Comment by swapnilsparsh** [comment]
> @swapnilsparsh I have tried a lot but the **markdown autodocs** is giving so many errors and the resources to resolve the same are almost none.

Do you want to resolve this issue or not?🙂

**Comment by DarkSoul26** [comment]
Sorry @swapnilsparsh, you can assign this task to anyone else. I couldn't resolve it.

**Comment by SahanAmarsha** [comment]
I would like to work on this issue 😀  @swapnilsparsh
