### ISSUE TITLE
Discord Button

### ISSUE THREAD

**Issue by jatiinyadav** [swapnilsparsh/DevEmpire#66]
1. At smaller screen sizes Discord Button should not stretch.

![InkedScreenshot 2021-10-08 143831_LI](https://user-images.githubusercontent.com/73248007/136530309-4142a1f8-ad51-4409-abd8-dc89569243e5.jpg)

2. It should look like this:-
![Screenshot 2021-10-08 144126](https://user-images.githubusercontent.com/73248007/136530507-9d6ed24d-e6dd-4e70-a7a9-d625877c6221.png)

**Comment by alifsiregar** [comment]
Hi @jatiinyadav, may I take this issue? Thanks!

**Comment by alifsiregar** [comment]
> @alifsiregar You have to make changes in style.scss

I did. The issue is that every time I made any changes in the style.scss, the generated style.css would delete some styling from the previous style.css. It's exactly like [this](https://github.com/swapnilsparsh/DevEmpire/pull/70#issuecomment-939228734) issue.

**Comment by swapnilsparsh** [comment]
@alifsiregar Issure resolved.
