### ISSUE TITLE
Add a Filter Option in Web Dev Page

### ISSUE THREAD

**Issue by swapnilsparsh** [swapnilsparsh/DevEmpire#7]
Hint: You have to add a label in `Web-dev-data.js` then you can use it to filter out the option from the given options.

**Comment by swapnilsparsh** [comment]
> Hi @swapnilsparsh , what should that filter actually filter? Is it a kind of dropdown?

Hi @Bhavin789 
It should not be in the dropdown.
You have to show all the filter options on the page adjacent to each other so the user can choose any of them if he/she wants.

**Comment by Bhavin789** [comment]
Got it. Kind of a series of labels next to the search maybe with some pre-defined categories right? Like `Icons` , `Illustration` etc.
![image](https://user-images.githubusercontent.com/15359575/135516786-0fef75aa-5599-4667-8040-20b6c702db19.png)

**Comment by swapnilsparsh** [comment]
> Got it. Kind of a series of labels next to the search maybe with some pre-defined categories right? Like `Icons` , `Illustration` etc. ![image](https://user-images.githubusercontent.com/15359575/135516786-0fef75aa-5599-4667-8040-20b6c702db19.png)

Yes.....

**Comment by Bhavin789** [comment]
Awesome, will check for some options here. Thanks for the clarity 👍 .

**Comment by swapnilsparsh** [comment]
> Awesome, will check for some options here. Thanks for the clarity 👍 .

Would you like to work on this issue, so I will assign this to you. ?

**Comment by tnmyk** [comment]
I would like to work on this too! Although in `Web-dev-data.js` , only one object has label property.

**Comment by swapnilsparsh** [comment]
> I would like to work on this too! Although in `Web-dev-data.js` , only one object has label property.

You have to make it for others 😅
