### ISSUE TITLE
Links in Web Dev section not working.

### ISSUE THREAD

**Issue by udz-codes** [swapnilsparsh/DevEmpire#80]
**Describe the bug**
All links in Web Dev page are not working

**To Reproduce**
1. Go to [link](https://devempire.netlify.app/webdev)
2. Click on Any of the items
3. See that it is not working

**Expected behavior**
The expected behaviour is that when we click on any link, it should redirect us to their page.

**Comment by swapnilsparsh** [comment]
@udz-codes Good Luck 🙂
