### ISSUE TITLE
Improve README.md

### ISSUE THREAD

**Issue by rushikeshadhav** [swapnilsparsh/DevEmpire#85]
**Is your feature request related to a problem? Please describe.**
Some Installation steps needs to be added

**Comment by swapnilsparsh** [comment]
> **Is your feature request related to a problem? Please describe.** Some Installation steps needs to be added

Every installation step is already there in README, so no need for this issue.

**Comment by rushikeshadhav** [comment]
hey @swapnilsparsh I mean steps like making a new branch and how to merge forked repo with original repo are missing

**Comment by rushikeshadhav** [comment]
How to contribute can also be added
1. How to commit (command)
2. How to raise a PR (command)
