### ISSUE TITLE
Toggle Feature for Menu's hamburger icon

### ISSUE THREAD

**Issue by aditi2906** [swapnilsparsh/DevEmpire#86]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by swapnilsparsh** [comment]
@aditi2906 Can you please provide a SS of the issue?

**Comment by aditi2906** [comment]
Initial:



![image](https://user-images.githubusercontent.com/61978541/144702650-f38a18f3-30fa-4dd6-852d-861454f3a293.png)

**Comment by swapnilsparsh** [comment]
> Initial: ![image](https://user-images.githubusercontent.com/61978541/144702666-b113fa74-cf09-4560-8aac-17f2ab7f6c56.png)
> 
> post toggling: ![image](https://user-images.githubusercontent.com/61978541/144702650-f38a18f3-30fa-4dd6-852d-861454f3a293.png)

I have assigned you the issue and Good Luck 🙂

**Comment by subhradwip01** [comment]
I would like to work on that issue. Can you please assign it to me?

**Comment by swapnilsparsh** [comment]
> I would like to work on that issue. Can you please assign it to me?

Good Luck 👍🏻

**Comment by unnati-dot** [comment]
Can i work on this issue?

**Comment by swapnilsparsh** [comment]
> Can i work on this issue?

Good Luck 👍🏻

**Comment by swapnilsparsh** [comment]
#95 Resolved
