### ISSUE TITLE
Hover on card animation to increase User Experience

### ISSUE THREAD

**Issue by devstardude** [swapnilsparsh/DevEmpire#87]
### Possible Feature
When you take your cursor on a particular card that shows information about fellowships and programs, there should be some change in card appearance so that it's differentiable from other card rendering among it, to make the User Experience better.

### Possible Solution
There is a Box shadow property on the card, When the user moves his cursor on a card the shadow should darken more to make it visually different from other cards

### Implementation
I've put `box-shadow` property in hover and added a `transition` property too, to make the hover animation smooth. The looks much better on cursor hover now.

I'll make the PR for the same issue, please review it. Thanks.

**Comment by swapnilsparsh** [comment]
Sorry but it's not required.

> ### Possible Feature
> When you take your cursor on a particular card that shows information about fellowships and programs, there should be some change in card appearance so that it's differentiable from other card rendering among it, to make the User Experience better.
> 
> ### Possible Solution
> There is a Box shadow property on the card, When the user moves his cursor on a card the shadow should darken more to make it visually different from other cards
> 
> ### Implementation
> I've put `box-shadow` property in hover and added a `transition` property too, to make the hover animation smooth. The looks much better on cursor hover now.
> 
> I'll make the PR for the same issue, please review it. Thanks.
