### ISSUE TITLE
How to raise a PR add to README.md

### ISSUE THREAD

**Issue by rushikeshadhav** [swapnilsparsh/DevEmpire#91]
**Is your feature request related to a problem? Please describe.**
Some steps to install repo locally are missing like creating a new branch

**Describe the solution you'd like**
1.Creating a new branch,
2. Upstream command
3. Merging forked with original repo
3. How to commit 
4. Raise a PR command must be added

If you still find this useless you are free to close this :)

**Comment by swapnilsparsh** [comment]
> 

Not required
