### ISSUE TITLE
Responsive problem at card section

### ISSUE THREAD

**Issue by Harsh2220** [swapnilsparsh/DevEmpire#93]
Responsive problem in card - about section text responsive.

Steps: 
1) Go To : https://devempire.netlify.app/ambassador
2) select Dimensions: Galaxy Fold

Smartphone: 
Device: Galaxy Fold

Screenshots:
![DevEmpire](https://user-images.githubusercontent.com/63700777/149085033-6ea51ad6-59bb-4649-a1ed-0099d83b9a75.jpg)

**Comment by swapnilsparsh** [comment]
@Harsh2220 Fix it and Good luck 👍🏻
