### ISSUE TITLE
View More button

### ISSUE THREAD

**Issue by swapnilsparsh** [swapnilsparsh/DevEmpire#96]
Add a view more button which should appear on every card and it should redirect to that particular website.

1. Follow the proper [color codes](https://github.com/swapnilsparsh/DevEmpire/blob/master/CONTRIBUTING.md#color-codes-) 
2. UI/UX should be clean.

**Comment by rockingrohit9639** [comment]
> Add a view more button which should appear on every card and it should redirect to that particular website.
> 
> 1. Follow the proper [color codes](https://github.com/swapnilsparsh/DevEmpire/blob/master/CONTRIBUTING.md#color-codes-)
> 2. UI/UX should be clean.

I would like to work on this issue @swapnilsparsh

**Comment by swapnilsparsh** [comment]
> > Add a view more button which should appear on every card and it should redirect to that particular website.
> > 
> > 1. Follow the proper [color codes](https://github.com/swapnilsparsh/DevEmpire/blob/master/CONTRIBUTING.md#color-codes-)
> > 2. UI/UX should be clean.
> 
> I would like to work on this issue @swapnilsparsh

Good Luck t👍🏻

**Comment by rockingrohit9639** [comment]
Hii @swapnilsparsh Can you please tell me more like where do you want to have the read more button? A screenshot will be perfect. Thank you.

**Comment by swapnilsparsh** [comment]
> @swapnilsparsh
> 
> I have done the task and it is looking like this. Please have a look at it and tell me if there is any changes required.
> 
> ![image](https://user-images.githubusercontent.com/40729749/153745105-af1b2022-d299-4fb9-8c59-504a29566cd4.png)

It looks great you have to remove the <a> tag from the whole card and apply the redirecting link <a> tag to View More only.

**Comment by rockingrohit9639** [comment]
> > @swapnilsparsh
> > I have done the task and it is looking like this. Please have a look at it and tell me if there is any changes required.
> > ![image](https://user-images.githubusercontent.com/40729749/153745105-af1b2022-d299-4fb9-8c59-504a29566cd4.png)
> 
> It looks great you have to remove the tag from the whole card and apply the redirecting link tag to View More only.

I have done the changes and made a PR. Please have a look at it @swapnilsparsh
